export const MINIMUM_SUPPORTED_EXTENSION_VERSION = process.env
  .NEXT_PUBLIC_MINIMUM_EXTENSION_VERSION as string;
export const CHROMIMUM_INSTALL_EXTENSION_URL = process.env
  .NEXT_PUBLIC_CHROMIMUM_INSTALL_EXTENSION_URL as string;
export const ALCHEMY_API_KEY = process.env
  .NEXT_PUBLIC_ALCHEMY_API_KEY as string;
if (!ALCHEMY_API_KEY) {
  throw new Error("Missing ALCHEMY_API_KEY");
}
