export const MINIMUM_SUPPORTED_EXTENSION_VERSION = process.env
  .NEXT_PUBLIC_MINIMUM_EXTENSION_VERSION as string;
export const CHROMIMUM_INSTALL_EXTENSION_URL = process.env
  .NEXT_PUBLIC_CHROMIMUM_INSTALL_EXTENSION_URL as string;
export const ALCHEMY_API_KEY = process.env
  .NEXT_PUBLIC_ALCHEMY_API_KEY as string;
export const BLOWFISH_V2_ENABLED =
  process.env.NEXT_PUBLIC_BLOWFISH_V2_ENABLED === "true";
export const BLOWFISH_PORTAL_API_BASE_URL = process.env
  .NEXT_PUBLIC_BLOWFISH_PORTAL_API_BASE_URL as string;
