/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DownloadBlocklist200ResponseBloomFilter } from './DownloadBlocklist200ResponseBloomFilter';
import {
    DownloadBlocklist200ResponseBloomFilterFromJSON,
    DownloadBlocklist200ResponseBloomFilterFromJSONTyped,
    DownloadBlocklist200ResponseBloomFilterToJSON,
} from './DownloadBlocklist200ResponseBloomFilter';

/**
 * 
 * @export
 * @interface DownloadBlocklist200Response
 */
export interface DownloadBlocklist200Response {
    /**
     * 
     * @type {DownloadBlocklist200ResponseBloomFilter}
     * @memberof DownloadBlocklist200Response
     */
    bloomFilter: DownloadBlocklist200ResponseBloomFilter;
    /**
     * 
     * @type {Array<string>}
     * @memberof DownloadBlocklist200Response
     */
    recentlyAdded: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DownloadBlocklist200Response
     */
    recentlyRemoved: Array<string>;
}

/**
 * Check if a given object implements the DownloadBlocklist200Response interface.
 */
export function instanceOfDownloadBlocklist200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bloomFilter" in value;
    isInstance = isInstance && "recentlyAdded" in value;
    isInstance = isInstance && "recentlyRemoved" in value;

    return isInstance;
}

export function DownloadBlocklist200ResponseFromJSON(json: any): DownloadBlocklist200Response {
    return DownloadBlocklist200ResponseFromJSONTyped(json, false);
}

export function DownloadBlocklist200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadBlocklist200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bloomFilter': DownloadBlocklist200ResponseBloomFilterFromJSON(json['bloomFilter']),
        'recentlyAdded': json['recentlyAdded'],
        'recentlyRemoved': json['recentlyRemoved'],
    };
}

export function DownloadBlocklist200ResponseToJSON(value?: DownloadBlocklist200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bloomFilter': DownloadBlocklist200ResponseBloomFilterToJSON(value.bloomFilter),
        'recentlyAdded': value.recentlyAdded,
        'recentlyRemoved': value.recentlyRemoved,
    };
}

