/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvmAmount
 */
export interface EvmAmount {
    /**
     * The value of the amount after the state change occurs
     * @type {string}
     * @memberof EvmAmount
     */
    after: string;
    /**
     * The value of the amount before the state change occurs
     * @type {string}
     * @memberof EvmAmount
     */
    before: string;
}

/**
 * Check if a given object implements the EvmAmount interface.
 */
export function instanceOfEvmAmount(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "after" in value;
    isInstance = isInstance && "before" in value;

    return isInstance;
}

export function EvmAmountFromJSON(json: any): EvmAmount {
    return EvmAmountFromJSONTyped(json, false);
}

export function EvmAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmAmount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'after': json['after'],
        'before': json['before'],
    };
}

export function EvmAmountToJSON(value?: EvmAmount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'after': value.after,
        'before': value.before,
    };
}

