/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmExpectedStateChangesInnerRawInfo } from './EvmExpectedStateChangesInnerRawInfo';
import {
    EvmExpectedStateChangesInnerRawInfoFromJSON,
    EvmExpectedStateChangesInnerRawInfoFromJSONTyped,
    EvmExpectedStateChangesInnerRawInfoToJSON,
} from './EvmExpectedStateChangesInnerRawInfo';

/**
 * 
 * @export
 * @interface EvmExpectedStateChangesInner
 */
export interface EvmExpectedStateChangesInner {
    /**
     * Computed explanation of the state change that can be directly presented to the end-user. While the API is still in development, we suggest integrators expose this in their signing UI if they encounter a `rawInfo.kind` they don't recognize.
     * @type {string}
     * @memberof EvmExpectedStateChangesInner
     */
    humanReadableDiff: string;
    /**
     * 
     * @type {EvmExpectedStateChangesInnerRawInfo}
     * @memberof EvmExpectedStateChangesInner
     */
    rawInfo: EvmExpectedStateChangesInnerRawInfo;
}

/**
 * Check if a given object implements the EvmExpectedStateChangesInner interface.
 */
export function instanceOfEvmExpectedStateChangesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "humanReadableDiff" in value;
    isInstance = isInstance && "rawInfo" in value;

    return isInstance;
}

export function EvmExpectedStateChangesInnerFromJSON(json: any): EvmExpectedStateChangesInner {
    return EvmExpectedStateChangesInnerFromJSONTyped(json, false);
}

export function EvmExpectedStateChangesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmExpectedStateChangesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'humanReadableDiff': json['humanReadableDiff'],
        'rawInfo': EvmExpectedStateChangesInnerRawInfoFromJSON(json['rawInfo']),
    };
}

export function EvmExpectedStateChangesInnerToJSON(value?: EvmExpectedStateChangesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'humanReadableDiff': value.humanReadableDiff,
        'rawInfo': EvmExpectedStateChangesInnerRawInfoToJSON(value.rawInfo),
    };
}

