/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmStateChangeErc721ApprovalData } from './EvmStateChangeErc721ApprovalData';
import {
    EvmStateChangeErc721ApprovalDataFromJSON,
    EvmStateChangeErc721ApprovalDataFromJSONTyped,
    EvmStateChangeErc721ApprovalDataToJSON,
} from './EvmStateChangeErc721ApprovalData';

/**
 * Approval request for a specific token in an ERC721 collection
 * @export
 * @interface EvmStateChangeErc721Approval
 */
export interface EvmStateChangeErc721Approval {
    /**
     * What kind of state change this object is
     * @type {string}
     * @memberof EvmStateChangeErc721Approval
     */
    kind: EvmStateChangeErc721ApprovalKindEnum;
    /**
     * 
     * @type {EvmStateChangeErc721ApprovalData}
     * @memberof EvmStateChangeErc721Approval
     */
    data: EvmStateChangeErc721ApprovalData;
}


/**
 * @export
 */
export const EvmStateChangeErc721ApprovalKindEnum = {
    Erc721Approval: 'ERC721_APPROVAL'
} as const;
export type EvmStateChangeErc721ApprovalKindEnum = typeof EvmStateChangeErc721ApprovalKindEnum[keyof typeof EvmStateChangeErc721ApprovalKindEnum];


/**
 * Check if a given object implements the EvmStateChangeErc721Approval interface.
 */
export function instanceOfEvmStateChangeErc721Approval(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function EvmStateChangeErc721ApprovalFromJSON(json: any): EvmStateChangeErc721Approval {
    return EvmStateChangeErc721ApprovalFromJSONTyped(json, false);
}

export function EvmStateChangeErc721ApprovalFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmStateChangeErc721Approval {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'data': EvmStateChangeErc721ApprovalDataFromJSON(json['data']),
    };
}

export function EvmStateChangeErc721ApprovalToJSON(value?: EvmStateChangeErc721Approval | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'data': EvmStateChangeErc721ApprovalDataToJSON(value.data),
    };
}

