/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmAddressInfo } from './EvmAddressInfo';
import {
    EvmAddressInfoFromJSON,
    EvmAddressInfoFromJSONTyped,
    EvmAddressInfoToJSON,
} from './EvmAddressInfo';
import type { EvmAsset } from './EvmAsset';
import {
    EvmAssetFromJSON,
    EvmAssetFromJSONTyped,
    EvmAssetToJSON,
} from './EvmAsset';

/**
 * Data associated with the state change
 * @export
 * @interface EvmStateChangeErc20PermitData
 */
export interface EvmStateChangeErc20PermitData {
    /**
     * 
     * @type {EvmAddressInfo}
     * @memberof EvmStateChangeErc20PermitData
     */
    contract: EvmAddressInfo;
    /**
     * 
     * @type {EvmAddressInfo}
     * @memberof EvmStateChangeErc20PermitData
     */
    owner: EvmAddressInfo;
    /**
     * 
     * @type {EvmAddressInfo}
     * @memberof EvmStateChangeErc20PermitData
     */
    spender: EvmAddressInfo;
    /**
     * Stringified base unit amount of the token
     * @type {string}
     * @memberof EvmStateChangeErc20PermitData
     */
    amount: string;
    /**
     * Stringified nonce number
     * @type {string}
     * @memberof EvmStateChangeErc20PermitData
     */
    nonce: string;
    /**
     * Unix timestamp when this permit will expire. Can be `null`: indicates no deadline.
     * @type {number}
     * @memberof EvmStateChangeErc20PermitData
     */
    deadline: number | null;
    /**
     * 
     * @type {EvmAsset}
     * @memberof EvmStateChangeErc20PermitData
     */
    asset: EvmAsset;
}

/**
 * Check if a given object implements the EvmStateChangeErc20PermitData interface.
 */
export function instanceOfEvmStateChangeErc20PermitData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contract" in value;
    isInstance = isInstance && "owner" in value;
    isInstance = isInstance && "spender" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "nonce" in value;
    isInstance = isInstance && "deadline" in value;
    isInstance = isInstance && "asset" in value;

    return isInstance;
}

export function EvmStateChangeErc20PermitDataFromJSON(json: any): EvmStateChangeErc20PermitData {
    return EvmStateChangeErc20PermitDataFromJSONTyped(json, false);
}

export function EvmStateChangeErc20PermitDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmStateChangeErc20PermitData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contract': EvmAddressInfoFromJSON(json['contract']),
        'owner': EvmAddressInfoFromJSON(json['owner']),
        'spender': EvmAddressInfoFromJSON(json['spender']),
        'amount': json['amount'],
        'nonce': json['nonce'],
        'deadline': json['deadline'],
        'asset': EvmAssetFromJSON(json['asset']),
    };
}

export function EvmStateChangeErc20PermitDataToJSON(value?: EvmStateChangeErc20PermitData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contract': EvmAddressInfoToJSON(value.contract),
        'owner': EvmAddressInfoToJSON(value.owner),
        'spender': EvmAddressInfoToJSON(value.spender),
        'amount': value.amount,
        'nonce': value.nonce,
        'deadline': value.deadline,
        'asset': EvmAssetToJSON(value.asset),
    };
}

