/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmAddressInfo } from './EvmAddressInfo';
import {
    EvmAddressInfoFromJSON,
    EvmAddressInfoFromJSONTyped,
    EvmAddressInfoToJSON,
} from './EvmAddressInfo';
import type { EvmAmount } from './EvmAmount';
import {
    EvmAmountFromJSON,
    EvmAmountFromJSONTyped,
    EvmAmountToJSON,
} from './EvmAmount';
import type { EvmAsset } from './EvmAsset';
import {
    EvmAssetFromJSON,
    EvmAssetFromJSONTyped,
    EvmAssetToJSON,
} from './EvmAsset';

/**
 * Data associated with the state change
 * @export
 * @interface EvmStateChangeErc20TransferData
 */
export interface EvmStateChangeErc20TransferData {
    /**
     * 
     * @type {EvmAddressInfo}
     * @memberof EvmStateChangeErc20TransferData
     */
    contract: EvmAddressInfo;
    /**
     * 
     * @type {EvmAmount}
     * @memberof EvmStateChangeErc20TransferData
     */
    amount: EvmAmount;
    /**
     * 
     * @type {EvmAsset}
     * @memberof EvmStateChangeErc20TransferData
     */
    asset: EvmAsset;
}

/**
 * Check if a given object implements the EvmStateChangeErc20TransferData interface.
 */
export function instanceOfEvmStateChangeErc20TransferData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contract" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "asset" in value;

    return isInstance;
}

export function EvmStateChangeErc20TransferDataFromJSON(json: any): EvmStateChangeErc20TransferData {
    return EvmStateChangeErc20TransferDataFromJSONTyped(json, false);
}

export function EvmStateChangeErc20TransferDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmStateChangeErc20TransferData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contract': EvmAddressInfoFromJSON(json['contract']),
        'amount': EvmAmountFromJSON(json['amount']),
        'asset': EvmAssetFromJSON(json['asset']),
    };
}

export function EvmStateChangeErc20TransferDataToJSON(value?: EvmStateChangeErc20TransferData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contract': EvmAddressInfoToJSON(value.contract),
        'amount': EvmAmountToJSON(value.amount),
        'asset': EvmAssetToJSON(value.asset),
    };
}

