/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmAddressInfo } from './EvmAddressInfo';
import {
    EvmAddressInfoFromJSON,
    EvmAddressInfoFromJSONTyped,
    EvmAddressInfoToJSON,
} from './EvmAddressInfo';
import type { EvmAmount } from './EvmAmount';
import {
    EvmAmountFromJSON,
    EvmAmountFromJSONTyped,
    EvmAmountToJSON,
} from './EvmAmount';
import type { EvmNativeAsset } from './EvmNativeAsset';
import {
    EvmNativeAssetFromJSON,
    EvmNativeAssetFromJSONTyped,
    EvmNativeAssetToJSON,
} from './EvmNativeAsset';

/**
 * Data associated with the state change
 * @export
 * @interface EvmStateChangeNativeAssetTransferData
 */
export interface EvmStateChangeNativeAssetTransferData {
    /**
     * 
     * @type {EvmAddressInfo}
     * @memberof EvmStateChangeNativeAssetTransferData
     */
    contract: EvmAddressInfo;
    /**
     * 
     * @type {EvmAmount}
     * @memberof EvmStateChangeNativeAssetTransferData
     */
    amount: EvmAmount;
    /**
     * 
     * @type {EvmNativeAsset}
     * @memberof EvmStateChangeNativeAssetTransferData
     */
    asset: EvmNativeAsset;
}

/**
 * Check if a given object implements the EvmStateChangeNativeAssetTransferData interface.
 */
export function instanceOfEvmStateChangeNativeAssetTransferData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contract" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "asset" in value;

    return isInstance;
}

export function EvmStateChangeNativeAssetTransferDataFromJSON(json: any): EvmStateChangeNativeAssetTransferData {
    return EvmStateChangeNativeAssetTransferDataFromJSONTyped(json, false);
}

export function EvmStateChangeNativeAssetTransferDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmStateChangeNativeAssetTransferData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contract': EvmAddressInfoFromJSON(json['contract']),
        'amount': EvmAmountFromJSON(json['amount']),
        'asset': EvmNativeAssetFromJSON(json['asset']),
    };
}

export function EvmStateChangeNativeAssetTransferDataToJSON(value?: EvmStateChangeNativeAssetTransferData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contract': EvmAddressInfoToJSON(value.contract),
        'amount': EvmAmountToJSON(value.amount),
        'asset': EvmNativeAssetToJSON(value.asset),
    };
}

