/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmSignTypedDataDataTypesEIP712DomainInner } from './EvmSignTypedDataDataTypesEIP712DomainInner';
import {
    EvmSignTypedDataDataTypesEIP712DomainInnerFromJSON,
    EvmSignTypedDataDataTypesEIP712DomainInnerFromJSONTyped,
    EvmSignTypedDataDataTypesEIP712DomainInnerToJSON,
} from './EvmSignTypedDataDataTypesEIP712DomainInner';

/**
 * 
 * @export
 * @interface EvmSignTypedDataDataTypes
 */
export interface EvmSignTypedDataDataTypes {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<EvmSignTypedDataDataTypesEIP712DomainInner>}
     * @memberof EvmSignTypedDataDataTypes
     */
    eIP712Domain?: Array<EvmSignTypedDataDataTypesEIP712DomainInner>;
}

/**
 * Check if a given object implements the EvmSignTypedDataDataTypes interface.
 */
export function instanceOfEvmSignTypedDataDataTypes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EvmSignTypedDataDataTypesFromJSON(json: any): EvmSignTypedDataDataTypes {
    return EvmSignTypedDataDataTypesFromJSONTyped(json, false);
}

export function EvmSignTypedDataDataTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmSignTypedDataDataTypes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'eIP712Domain': !exists(json, 'EIP712Domain') ? undefined : ((json['EIP712Domain'] as Array<any>).map(EvmSignTypedDataDataTypesEIP712DomainInnerFromJSON)),
    };
}

export function EvmSignTypedDataDataTypesToJSON(value?: EvmSignTypedDataDataTypes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'EIP712Domain': value.eIP712Domain === undefined ? undefined : ((value.eIP712Domain as Array<any>).map(EvmSignTypedDataDataTypesEIP712DomainInnerToJSON)),
    };
}

