/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmStateChangeNativeAssetTransferData } from './EvmStateChangeNativeAssetTransferData';
import {
    EvmStateChangeNativeAssetTransferDataFromJSON,
    EvmStateChangeNativeAssetTransferDataFromJSONTyped,
    EvmStateChangeNativeAssetTransferDataToJSON,
} from './EvmStateChangeNativeAssetTransferData';

/**
 * ETH transfers
 * @export
 * @interface EvmStateChangeNativeAssetTransfer
 */
export interface EvmStateChangeNativeAssetTransfer {
    /**
     * What kind of state change this object is
     * @type {string}
     * @memberof EvmStateChangeNativeAssetTransfer
     */
    kind: EvmStateChangeNativeAssetTransferKindEnum;
    /**
     * 
     * @type {EvmStateChangeNativeAssetTransferData}
     * @memberof EvmStateChangeNativeAssetTransfer
     */
    data: EvmStateChangeNativeAssetTransferData;
}


/**
 * @export
 */
export const EvmStateChangeNativeAssetTransferKindEnum = {
    NativeAssetTransfer: 'NATIVE_ASSET_TRANSFER'
} as const;
export type EvmStateChangeNativeAssetTransferKindEnum = typeof EvmStateChangeNativeAssetTransferKindEnum[keyof typeof EvmStateChangeNativeAssetTransferKindEnum];


/**
 * Check if a given object implements the EvmStateChangeNativeAssetTransfer interface.
 */
export function instanceOfEvmStateChangeNativeAssetTransfer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function EvmStateChangeNativeAssetTransferFromJSON(json: any): EvmStateChangeNativeAssetTransfer {
    return EvmStateChangeNativeAssetTransferFromJSONTyped(json, false);
}

export function EvmStateChangeNativeAssetTransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmStateChangeNativeAssetTransfer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'data': EvmStateChangeNativeAssetTransferDataFromJSON(json['data']),
    };
}

export function EvmStateChangeNativeAssetTransferToJSON(value?: EvmStateChangeNativeAssetTransfer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'data': EvmStateChangeNativeAssetTransferDataToJSON(value.data),
    };
}

