/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvmSignTypedDataDataDomain
 */
export interface EvmSignTypedDataDataDomain {
    /**
     * 
     * @type {string}
     * @memberof EvmSignTypedDataDataDomain
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EvmSignTypedDataDataDomain
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof EvmSignTypedDataDataDomain
     */
    chainId?: string;
    /**
     * 
     * @type {string}
     * @memberof EvmSignTypedDataDataDomain
     */
    verifyingContract?: string;
}

/**
 * Check if a given object implements the EvmSignTypedDataDataDomain interface.
 */
export function instanceOfEvmSignTypedDataDataDomain(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EvmSignTypedDataDataDomainFromJSON(json: any): EvmSignTypedDataDataDomain {
    return EvmSignTypedDataDataDomainFromJSONTyped(json, false);
}

export function EvmSignTypedDataDataDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmSignTypedDataDataDomain {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'chainId': !exists(json, 'chainId') ? undefined : json['chainId'],
        'verifyingContract': !exists(json, 'verifyingContract') ? undefined : json['verifyingContract'],
    };
}

export function EvmSignTypedDataDataDomainToJSON(value?: EvmSignTypedDataDataDomain | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'version': value.version,
        'chainId': value.chainId,
        'verifyingContract': value.verifyingContract,
    };
}

