/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmStateChangeErc20ApprovalData } from './EvmStateChangeErc20ApprovalData';
import {
    EvmStateChangeErc20ApprovalDataFromJSON,
    EvmStateChangeErc20ApprovalDataFromJSONTyped,
    EvmStateChangeErc20ApprovalDataToJSON,
} from './EvmStateChangeErc20ApprovalData';

/**
 * Approval request to transfer user's ERC20 tokens
 * @export
 * @interface EvmStateChangeErc20Approval
 */
export interface EvmStateChangeErc20Approval {
    /**
     * What kind of state change this object is
     * @type {string}
     * @memberof EvmStateChangeErc20Approval
     */
    kind: EvmStateChangeErc20ApprovalKindEnum;
    /**
     * 
     * @type {EvmStateChangeErc20ApprovalData}
     * @memberof EvmStateChangeErc20Approval
     */
    data: EvmStateChangeErc20ApprovalData;
}


/**
 * @export
 */
export const EvmStateChangeErc20ApprovalKindEnum = {
    Erc20Approval: 'ERC20_APPROVAL'
} as const;
export type EvmStateChangeErc20ApprovalKindEnum = typeof EvmStateChangeErc20ApprovalKindEnum[keyof typeof EvmStateChangeErc20ApprovalKindEnum];


/**
 * Check if a given object implements the EvmStateChangeErc20Approval interface.
 */
export function instanceOfEvmStateChangeErc20Approval(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function EvmStateChangeErc20ApprovalFromJSON(json: any): EvmStateChangeErc20Approval {
    return EvmStateChangeErc20ApprovalFromJSONTyped(json, false);
}

export function EvmStateChangeErc20ApprovalFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmStateChangeErc20Approval {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'data': EvmStateChangeErc20ApprovalDataFromJSON(json['data']),
    };
}

export function EvmStateChangeErc20ApprovalToJSON(value?: EvmStateChangeErc20Approval | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'data': EvmStateChangeErc20ApprovalDataToJSON(value.data),
    };
}

