/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmStateChangeErc721TransferData } from './EvmStateChangeErc721TransferData';
import {
    EvmStateChangeErc721TransferDataFromJSON,
    EvmStateChangeErc721TransferDataFromJSONTyped,
    EvmStateChangeErc721TransferDataToJSON,
} from './EvmStateChangeErc721TransferData';

/**
 * ERC721 NFT transfers
 * @export
 * @interface EvmStateChangeErc721Transfer
 */
export interface EvmStateChangeErc721Transfer {
    /**
     * What kind of state change this object is
     * @type {string}
     * @memberof EvmStateChangeErc721Transfer
     */
    kind: EvmStateChangeErc721TransferKindEnum;
    /**
     * 
     * @type {EvmStateChangeErc721TransferData}
     * @memberof EvmStateChangeErc721Transfer
     */
    data: EvmStateChangeErc721TransferData;
}


/**
 * @export
 */
export const EvmStateChangeErc721TransferKindEnum = {
    Erc721Transfer: 'ERC721_TRANSFER'
} as const;
export type EvmStateChangeErc721TransferKindEnum = typeof EvmStateChangeErc721TransferKindEnum[keyof typeof EvmStateChangeErc721TransferKindEnum];


/**
 * Check if a given object implements the EvmStateChangeErc721Transfer interface.
 */
export function instanceOfEvmStateChangeErc721Transfer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function EvmStateChangeErc721TransferFromJSON(json: any): EvmStateChangeErc721Transfer {
    return EvmStateChangeErc721TransferFromJSONTyped(json, false);
}

export function EvmStateChangeErc721TransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmStateChangeErc721Transfer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'data': EvmStateChangeErc721TransferDataFromJSON(json['data']),
    };
}

export function EvmStateChangeErc721TransferToJSON(value?: EvmStateChangeErc721Transfer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'data': EvmStateChangeErc721TransferDataToJSON(value.data),
    };
}

