/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvmSignTypedDataDataTypesEIP712DomainInner
 */
export interface EvmSignTypedDataDataTypesEIP712DomainInner {
    /**
     * 
     * @type {string}
     * @memberof EvmSignTypedDataDataTypesEIP712DomainInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EvmSignTypedDataDataTypesEIP712DomainInner
     */
    type?: string;
}

/**
 * Check if a given object implements the EvmSignTypedDataDataTypesEIP712DomainInner interface.
 */
export function instanceOfEvmSignTypedDataDataTypesEIP712DomainInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EvmSignTypedDataDataTypesEIP712DomainInnerFromJSON(json: any): EvmSignTypedDataDataTypesEIP712DomainInner {
    return EvmSignTypedDataDataTypesEIP712DomainInnerFromJSONTyped(json, false);
}

export function EvmSignTypedDataDataTypesEIP712DomainInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmSignTypedDataDataTypesEIP712DomainInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function EvmSignTypedDataDataTypesEIP712DomainInnerToJSON(value?: EvmSignTypedDataDataTypesEIP712DomainInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': value.type,
    };
}

