/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmStateChangeErc1155TransferData } from './EvmStateChangeErc1155TransferData';
import {
    EvmStateChangeErc1155TransferDataFromJSON,
    EvmStateChangeErc1155TransferDataFromJSONTyped,
    EvmStateChangeErc1155TransferDataToJSON,
} from './EvmStateChangeErc1155TransferData';

/**
 * ERC1155 transfers
 * @export
 * @interface EvmStateChangeErc1155Transfer
 */
export interface EvmStateChangeErc1155Transfer {
    /**
     * What kind of state change this object is
     * @type {string}
     * @memberof EvmStateChangeErc1155Transfer
     */
    kind: EvmStateChangeErc1155TransferKindEnum;
    /**
     * 
     * @type {EvmStateChangeErc1155TransferData}
     * @memberof EvmStateChangeErc1155Transfer
     */
    data: EvmStateChangeErc1155TransferData;
}


/**
 * @export
 */
export const EvmStateChangeErc1155TransferKindEnum = {
    Erc1155Transfer: 'ERC1155_TRANSFER'
} as const;
export type EvmStateChangeErc1155TransferKindEnum = typeof EvmStateChangeErc1155TransferKindEnum[keyof typeof EvmStateChangeErc1155TransferKindEnum];


/**
 * Check if a given object implements the EvmStateChangeErc1155Transfer interface.
 */
export function instanceOfEvmStateChangeErc1155Transfer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function EvmStateChangeErc1155TransferFromJSON(json: any): EvmStateChangeErc1155Transfer {
    return EvmStateChangeErc1155TransferFromJSONTyped(json, false);
}

export function EvmStateChangeErc1155TransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmStateChangeErc1155Transfer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'data': EvmStateChangeErc1155TransferDataFromJSON(json['data']),
    };
}

export function EvmStateChangeErc1155TransferToJSON(value?: EvmStateChangeErc1155Transfer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'data': EvmStateChangeErc1155TransferDataToJSON(value.data),
    };
}

