/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssetPrice } from './AssetPrice';
import {
    AssetPriceFromJSON,
    AssetPriceFromJSONTyped,
    AssetPriceToJSON,
} from './AssetPrice';
import type { EvmAddressInfo } from './EvmAddressInfo';
import {
    EvmAddressInfoFromJSON,
    EvmAddressInfoFromJSONTyped,
    EvmAddressInfoToJSON,
} from './EvmAddressInfo';
import type { EvmAmount } from './EvmAmount';
import {
    EvmAmountFromJSON,
    EvmAmountFromJSONTyped,
    EvmAmountToJSON,
} from './EvmAmount';

/**
 * Data associated with the state change
 * @export
 * @interface EvmStateChangeErc721ApprovalForAllData
 */
export interface EvmStateChangeErc721ApprovalForAllData {
    /**
     * 
     * @type {EvmAmount}
     * @memberof EvmStateChangeErc721ApprovalForAllData
     */
    amount: EvmAmount;
    /**
     * 
     * @type {EvmAddressInfo}
     * @memberof EvmStateChangeErc721ApprovalForAllData
     */
    contract: EvmAddressInfo;
    /**
     * 
     * @type {string}
     * @memberof EvmStateChangeErc721ApprovalForAllData
     */
    name: string;
    /**
     * 
     * @type {EvmAddressInfo}
     * @memberof EvmStateChangeErc721ApprovalForAllData
     */
    owner: EvmAddressInfo;
    /**
     * 
     * @type {EvmAddressInfo}
     * @memberof EvmStateChangeErc721ApprovalForAllData
     */
    spender: EvmAddressInfo;
    /**
     * 
     * @type {string}
     * @memberof EvmStateChangeErc721ApprovalForAllData
     */
    symbol: string;
    /**
     * 
     * @type {AssetPrice}
     * @memberof EvmStateChangeErc721ApprovalForAllData
     */
    assetPrice: AssetPrice | null;
}

/**
 * Check if a given object implements the EvmStateChangeErc721ApprovalForAllData interface.
 */
export function instanceOfEvmStateChangeErc721ApprovalForAllData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "contract" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "owner" in value;
    isInstance = isInstance && "spender" in value;
    isInstance = isInstance && "symbol" in value;
    isInstance = isInstance && "assetPrice" in value;

    return isInstance;
}

export function EvmStateChangeErc721ApprovalForAllDataFromJSON(json: any): EvmStateChangeErc721ApprovalForAllData {
    return EvmStateChangeErc721ApprovalForAllDataFromJSONTyped(json, false);
}

export function EvmStateChangeErc721ApprovalForAllDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmStateChangeErc721ApprovalForAllData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': EvmAmountFromJSON(json['amount']),
        'contract': EvmAddressInfoFromJSON(json['contract']),
        'name': json['name'],
        'owner': EvmAddressInfoFromJSON(json['owner']),
        'spender': EvmAddressInfoFromJSON(json['spender']),
        'symbol': json['symbol'],
        'assetPrice': AssetPriceFromJSON(json['assetPrice']),
    };
}

export function EvmStateChangeErc721ApprovalForAllDataToJSON(value?: EvmStateChangeErc721ApprovalForAllData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': EvmAmountToJSON(value.amount),
        'contract': EvmAddressInfoToJSON(value.contract),
        'name': value.name,
        'owner': EvmAddressInfoToJSON(value.owner),
        'spender': EvmAddressInfoToJSON(value.spender),
        'symbol': value.symbol,
        'assetPrice': AssetPriceToJSON(value.assetPrice),
    };
}

