/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvmSimulationFailedError
 */
export interface EvmSimulationFailedError {
    /**
     * 
     * @type {string}
     * @memberof EvmSimulationFailedError
     */
    kind: EvmSimulationFailedErrorKindEnum;
    /**
     * Human readable explanation of the error
     * @type {string}
     * @memberof EvmSimulationFailedError
     */
    humanReadableError: string;
    /**
     * Internal reason for the simulation failure
     * @type {string}
     * @memberof EvmSimulationFailedError
     */
    reason: string;
}


/**
 * @export
 */
export const EvmSimulationFailedErrorKindEnum = {
    SimulationFailed: 'SIMULATION_FAILED'
} as const;
export type EvmSimulationFailedErrorKindEnum = typeof EvmSimulationFailedErrorKindEnum[keyof typeof EvmSimulationFailedErrorKindEnum];


/**
 * Check if a given object implements the EvmSimulationFailedError interface.
 */
export function instanceOfEvmSimulationFailedError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "humanReadableError" in value;
    isInstance = isInstance && "reason" in value;

    return isInstance;
}

export function EvmSimulationFailedErrorFromJSON(json: any): EvmSimulationFailedError {
    return EvmSimulationFailedErrorFromJSONTyped(json, false);
}

export function EvmSimulationFailedErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmSimulationFailedError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'humanReadableError': json['humanReadableError'],
        'reason': json['reason'],
    };
}

export function EvmSimulationFailedErrorToJSON(value?: EvmSimulationFailedError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'humanReadableError': value.humanReadableError,
        'reason': value.reason,
    };
}

