/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvmTransactionError
 */
export interface EvmTransactionError {
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionError
     */
    kind: EvmTransactionErrorKindEnum;
    /**
     * Human readable explanation of the error
     * @type {string}
     * @memberof EvmTransactionError
     */
    humanReadableError: string;
    /**
     * For all the errors during the execution that do not have a revert reason. Like InvalidOpcode or LackOfFundForGasLimit.
     * @type {string}
     * @memberof EvmTransactionError
     */
    errorType: string;
}


/**
 * @export
 */
export const EvmTransactionErrorKindEnum = {
    TransactionError: 'TRANSACTION_ERROR'
} as const;
export type EvmTransactionErrorKindEnum = typeof EvmTransactionErrorKindEnum[keyof typeof EvmTransactionErrorKindEnum];


/**
 * Check if a given object implements the EvmTransactionError interface.
 */
export function instanceOfEvmTransactionError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "humanReadableError" in value;
    isInstance = isInstance && "errorType" in value;

    return isInstance;
}

export function EvmTransactionErrorFromJSON(json: any): EvmTransactionError {
    return EvmTransactionErrorFromJSONTyped(json, false);
}

export function EvmTransactionErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmTransactionError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'humanReadableError': json['humanReadableError'],
        'errorType': json['errorType'],
    };
}

export function EvmTransactionErrorToJSON(value?: EvmTransactionError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'humanReadableError': value.humanReadableError,
        'errorType': value.errorType,
    };
}

