/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specify the desired language for the returned warning messages and human-readable simulation results. If unknown, defaults to English.
 * @export
 */
export const Languages = {
    Am: 'am',
    Ar: 'ar',
    ArSa: 'ar-SA',
    ArEg: 'ar-EG',
    ArDz: 'ar-DZ',
    ArMa: 'ar-MA',
    ArIq: 'ar-IQ',
    ArJo: 'ar-JO',
    ArKw: 'ar-KW',
    ArLb: 'ar-LB',
    ArLy: 'ar-LY',
    ArOm: 'ar-OM',
    ArQa: 'ar-QA',
    ArSy: 'ar-SY',
    ArTn: 'ar-TN',
    ArAe: 'ar-AE',
    ArYe: 'ar-YE',
    Bn: 'bn',
    Fr: 'fr',
    FrBe: 'fr-BE',
    FrCa: 'fr-CA',
    FrFr: 'fr-FR',
    FrLu: 'fr-LU',
    FrCh: 'fr-CH',
    De: 'de',
    DeAt: 'de-AT',
    DeDe: 'de-DE',
    DeLi: 'de-LI',
    DeLu: 'de-LU',
    DeCh: 'de-CH',
    En: 'en',
    EnUs: 'en-US',
    EnGb: 'en-GB',
    EnCa: 'en-CA',
    EnAu: 'en-AU',
    EnNz: 'en-NZ',
    EnZa: 'en-ZA',
    EnIe: 'en-IE',
    EnIn: 'en-IN',
    EnSg: 'en-SG',
    EnJm: 'en-JM',
    EnBz: 'en-BZ',
    EnTt: 'en-TT',
    EnPh: 'en-PH',
    It: 'it',
    ItIt: 'it-IT',
    ItCh: 'it-CH',
    Ms: 'ms',
    MsBn: 'ms-BN',
    MsMy: 'ms-MY',
    Pt: 'pt',
    PtBr: 'pt-BR',
    PtPt: 'pt-PT',
    Ru: 'ru',
    RuRu: 'ru-RU',
    Es: 'es',
    EsAr: 'es-AR',
    EsBo: 'es-BO',
    EsCl: 'es-CL',
    EsCo: 'es-CO',
    EsCr: 'es-CR',
    EsCu: 'es-CU',
    EsDo: 'es-DO',
    EsEc: 'es-EC',
    EsSv: 'es-SV',
    EsGq: 'es-GQ',
    EsGt: 'es-GT',
    EsHn: 'es-HN',
    EsMx: 'es-MX',
    EsNi: 'es-NI',
    EsPa: 'es-PA',
    EsPy: 'es-PY',
    EsPe: 'es-PE',
    EsPh: 'es-PH',
    EsPr: 'es-PR',
    EsEs: 'es-ES',
    EsUs: 'es-US',
    EsUy: 'es-UY',
    EsVe: 'es-VE',
    Sw: 'sw',
    Tr: 'tr',
    TrTr: 'tr-TR',
    Fil: 'fil',
    GuIn: 'gu_IN',
    Ha: 'ha',
    Hi: 'hi',
    Id: 'id',
    Ig: 'ig',
    Ja: 'ja',
    Ko: 'ko',
    My: 'my',
    Pa: 'pa',
    Ta: 'ta',
    Th: 'th',
    Vi: 'vi',
    Yo: 'yo',
    ZhCn: 'zh_CN',
    ZhTw: 'zh_TW'
} as const;
export type Languages = typeof Languages[keyof typeof Languages];


export function LanguagesFromJSON(json: any): Languages {
    return LanguagesFromJSONTyped(json, false);
}

export function LanguagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Languages {
    return json as Languages;
}

export function LanguagesToJSON(value?: Languages | null): any {
    return value as any;
}

