/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MetaplexTokenStandard = {
    NonFungible: 'non_fungible',
    FungibleAsset: 'fungible_asset',
    Fungible: 'fungible',
    NonFungibleEdition: 'non_fungible_edition',
    Unknown: 'unknown'
} as const;
export type MetaplexTokenStandard = typeof MetaplexTokenStandard[keyof typeof MetaplexTokenStandard];


export function MetaplexTokenStandardFromJSON(json: any): MetaplexTokenStandard {
    return MetaplexTokenStandardFromJSONTyped(json, false);
}

export function MetaplexTokenStandardFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaplexTokenStandard {
    return json as MetaplexTokenStandard;
}

export function MetaplexTokenStandardToJSON(value?: MetaplexTokenStandard | null): any {
    return value as any;
}

