/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectWithDomainsPropertyOfTypeArray
 */
export interface ObjectWithDomainsPropertyOfTypeArray {
    /**
     * 
     * @type {Array<string>}
     * @memberof ObjectWithDomainsPropertyOfTypeArray
     */
    domains?: Array<string>;
}

/**
 * Check if a given object implements the ObjectWithDomainsPropertyOfTypeArray interface.
 */
export function instanceOfObjectWithDomainsPropertyOfTypeArray(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ObjectWithDomainsPropertyOfTypeArrayFromJSON(json: any): ObjectWithDomainsPropertyOfTypeArray {
    return ObjectWithDomainsPropertyOfTypeArrayFromJSONTyped(json, false);
}

export function ObjectWithDomainsPropertyOfTypeArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectWithDomainsPropertyOfTypeArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'domains': !exists(json, 'domains') ? undefined : json['domains'],
    };
}

export function ObjectWithDomainsPropertyOfTypeArrayToJSON(value?: ObjectWithDomainsPropertyOfTypeArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'domains': value.domains,
    };
}

