/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInner } from './ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInner';
import {
    ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerFromJSON,
    ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerFromJSONTyped,
    ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerToJSON,
} from './ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInner';
import type { ScanTransactionsSolana200ResponseSimulationResultsRawReturnData } from './ScanTransactionsSolana200ResponseSimulationResultsRawReturnData';
import {
    ScanTransactionsSolana200ResponseSimulationResultsRawReturnDataFromJSON,
    ScanTransactionsSolana200ResponseSimulationResultsRawReturnDataFromJSONTyped,
    ScanTransactionsSolana200ResponseSimulationResultsRawReturnDataToJSON,
} from './ScanTransactionsSolana200ResponseSimulationResultsRawReturnData';

/**
 * Raw results of the simulation
 * @export
 * @interface ScanTransactionsSolana200ResponseSimulationResultsRaw
 */
export interface ScanTransactionsSolana200ResponseSimulationResultsRaw {
    /**
     * Program instruction error causing the failure. Can be `null`.
     * @type {string}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsRaw
     */
    err: string | null;
    /**
     * Program logs generated during execution
     * @type {Array<string>}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsRaw
     */
    logs: Array<string>;
    /**
     * Account state post-simulation or null values on failure
     * @type {Array<ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInner>}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsRaw
     */
    accounts: Array<ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInner>;
    /**
     * 
     * @type {number}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsRaw
     */
    unitsConsumed: number;
    /**
     * 
     * @type {ScanTransactionsSolana200ResponseSimulationResultsRawReturnData}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsRaw
     */
    returnData: ScanTransactionsSolana200ResponseSimulationResultsRawReturnData | null;
}

/**
 * Check if a given object implements the ScanTransactionsSolana200ResponseSimulationResultsRaw interface.
 */
export function instanceOfScanTransactionsSolana200ResponseSimulationResultsRaw(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "err" in value;
    isInstance = isInstance && "logs" in value;
    isInstance = isInstance && "accounts" in value;
    isInstance = isInstance && "unitsConsumed" in value;
    isInstance = isInstance && "returnData" in value;

    return isInstance;
}

export function ScanTransactionsSolana200ResponseSimulationResultsRawFromJSON(json: any): ScanTransactionsSolana200ResponseSimulationResultsRaw {
    return ScanTransactionsSolana200ResponseSimulationResultsRawFromJSONTyped(json, false);
}

export function ScanTransactionsSolana200ResponseSimulationResultsRawFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionsSolana200ResponseSimulationResultsRaw {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'err': json['err'],
        'logs': json['logs'],
        'accounts': ((json['accounts'] as Array<any>).map(ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerFromJSON)),
        'unitsConsumed': json['unitsConsumed'],
        'returnData': ScanTransactionsSolana200ResponseSimulationResultsRawReturnDataFromJSON(json['returnData']),
    };
}

export function ScanTransactionsSolana200ResponseSimulationResultsRawToJSON(value?: ScanTransactionsSolana200ResponseSimulationResultsRaw | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'err': value.err,
        'logs': value.logs,
        'accounts': ((value.accounts as Array<any>).map(ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerToJSON)),
        'unitsConsumed': value.unitsConsumed,
        'returnData': ScanTransactionsSolana200ResponseSimulationResultsRawReturnDataToJSON(value.returnData),
    };
}

