/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An object that contains nullable fields with information about the estimated gas consumption of the simulated transaction
 * @export
 * @interface ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas
 */
export interface ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas {
    /**
     * A field that if the simulation was successful contains the estimated upper limit of gas usage for this transaction. The gasLimit should be viewed as an upper bound of how much gas the transaction can use, not as an accurate estimate how much it will realistically consume when submitted on-chain. Can be `null`.
     * @type {string}
     * @memberof ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas
     */
    gasLimit: string | null;
}

/**
 * Check if a given object implements the ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas interface.
 */
export function instanceOfScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "gasLimit" in value;

    return isInstance;
}

export function ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasFromJSON(json: any): ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas {
    return ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasFromJSONTyped(json, false);
}

export function ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gasLimit': json['gasLimit'],
    };
}

export function ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasToJSON(value?: ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gasLimit': value.gasLimit,
    };
}

