/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ActionEnum } from './ActionEnum';
import {
    ActionEnumFromJSON,
    ActionEnumFromJSONTyped,
    ActionEnumToJSON,
} from './ActionEnum';
import type { ScanTransactionsSolana200ResponseSimulationResults } from './ScanTransactionsSolana200ResponseSimulationResults';
import {
    ScanTransactionsSolana200ResponseSimulationResultsFromJSON,
    ScanTransactionsSolana200ResponseSimulationResultsFromJSONTyped,
    ScanTransactionsSolana200ResponseSimulationResultsToJSON,
} from './ScanTransactionsSolana200ResponseSimulationResults';
import type { WarningInner } from './WarningInner';
import {
    WarningInnerFromJSON,
    WarningInnerFromJSONTyped,
    WarningInnerToJSON,
} from './WarningInner';

/**
 * 
 * @export
 * @interface ScanTransactionsSolana200Response
 */
export interface ScanTransactionsSolana200Response {
    /**
     * 
     * @type {ActionEnum}
     * @memberof ScanTransactionsSolana200Response
     */
    action: ActionEnum;
    /**
     * An array of warnings generated from scanning the transactions. All these warnings won't be returned in a single response (some are mutually exclusive) but it is advisable that your UI can display multiple warnings. Warnings are returned sorted by severity, so if you can only show a user one warning, show them the one at the 0th index.
     * @type {Array<WarningInner>}
     * @memberof ScanTransactionsSolana200Response
     */
    warnings: Array<WarningInner>;
    /**
     * 
     * @type {ScanTransactionsSolana200ResponseSimulationResults}
     * @memberof ScanTransactionsSolana200Response
     */
    simulationResults: ScanTransactionsSolana200ResponseSimulationResults;
    /**
     * An enum value describing whether a program in the proposed transactions was either a known or suspected malicious program. Deprecated. Use `action` instead.
     * @type {string}
     * @memberof ScanTransactionsSolana200Response
     * @deprecated
     */
    status: ScanTransactionsSolana200ResponseStatusEnum;
}


/**
 * @export
 */
export const ScanTransactionsSolana200ResponseStatusEnum = {
    ChecksPassed: 'CHECKS_PASSED',
    SuspectedMalicious: 'SUSPECTED_MALICIOUS',
    KnownMalicious: 'KNOWN_MALICIOUS'
} as const;
export type ScanTransactionsSolana200ResponseStatusEnum = typeof ScanTransactionsSolana200ResponseStatusEnum[keyof typeof ScanTransactionsSolana200ResponseStatusEnum];


/**
 * Check if a given object implements the ScanTransactionsSolana200Response interface.
 */
export function instanceOfScanTransactionsSolana200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "warnings" in value;
    isInstance = isInstance && "simulationResults" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function ScanTransactionsSolana200ResponseFromJSON(json: any): ScanTransactionsSolana200Response {
    return ScanTransactionsSolana200ResponseFromJSONTyped(json, false);
}

export function ScanTransactionsSolana200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionsSolana200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': ActionEnumFromJSON(json['action']),
        'warnings': ((json['warnings'] as Array<any>).map(WarningInnerFromJSON)),
        'simulationResults': ScanTransactionsSolana200ResponseSimulationResultsFromJSON(json['simulationResults']),
        'status': json['status'],
    };
}

export function ScanTransactionsSolana200ResponseToJSON(value?: ScanTransactionsSolana200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': ActionEnumToJSON(value.action),
        'warnings': ((value.warnings as Array<any>).map(WarningInnerToJSON)),
        'simulationResults': ScanTransactionsSolana200ResponseSimulationResultsToJSON(value.simulationResults),
        'status': value.status,
    };
}

