/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmExpectedStateChangesInner } from './EvmExpectedStateChangesInner';
import {
    EvmExpectedStateChangesInnerFromJSON,
    EvmExpectedStateChangesInnerFromJSONTyped,
    EvmExpectedStateChangesInnerToJSON,
} from './EvmExpectedStateChangesInner';
import type { ScanTransactionsEvm200ResponseSimulationResultsAggregatedError } from './ScanTransactionsEvm200ResponseSimulationResultsAggregatedError';
import {
    ScanTransactionsEvm200ResponseSimulationResultsAggregatedErrorFromJSON,
    ScanTransactionsEvm200ResponseSimulationResultsAggregatedErrorFromJSONTyped,
    ScanTransactionsEvm200ResponseSimulationResultsAggregatedErrorToJSON,
} from './ScanTransactionsEvm200ResponseSimulationResultsAggregatedError';

/**
 * 
 * @export
 * @interface ScanTransactionsEvm200ResponseSimulationResultsAggregated
 */
export interface ScanTransactionsEvm200ResponseSimulationResultsAggregated {
    /**
     * 
     * @type {Array<EvmExpectedStateChangesInner>}
     * @memberof ScanTransactionsEvm200ResponseSimulationResultsAggregated
     */
    expectedStateChanges: Array<EvmExpectedStateChangesInner>;
    /**
     * 
     * @type {ScanTransactionsEvm200ResponseSimulationResultsAggregatedError}
     * @memberof ScanTransactionsEvm200ResponseSimulationResultsAggregated
     */
    error: ScanTransactionsEvm200ResponseSimulationResultsAggregatedError | null;
}

/**
 * Check if a given object implements the ScanTransactionsEvm200ResponseSimulationResultsAggregated interface.
 */
export function instanceOfScanTransactionsEvm200ResponseSimulationResultsAggregated(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "expectedStateChanges" in value;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function ScanTransactionsEvm200ResponseSimulationResultsAggregatedFromJSON(json: any): ScanTransactionsEvm200ResponseSimulationResultsAggregated {
    return ScanTransactionsEvm200ResponseSimulationResultsAggregatedFromJSONTyped(json, false);
}

export function ScanTransactionsEvm200ResponseSimulationResultsAggregatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionsEvm200ResponseSimulationResultsAggregated {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expectedStateChanges': ((json['expectedStateChanges'] as Array<any>).map(EvmExpectedStateChangesInnerFromJSON)),
        'error': ScanTransactionsEvm200ResponseSimulationResultsAggregatedErrorFromJSON(json['error']),
    };
}

export function ScanTransactionsEvm200ResponseSimulationResultsAggregatedToJSON(value?: ScanTransactionsEvm200ResponseSimulationResultsAggregated | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expectedStateChanges': ((value.expectedStateChanges as Array<any>).map(EvmExpectedStateChangesInnerToJSON)),
        'error': ScanTransactionsEvm200ResponseSimulationResultsAggregatedErrorToJSON(value.error),
    };
}

