/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EvmStateChangeErc1155ApprovalForAll,
    instanceOfEvmStateChangeErc1155ApprovalForAll,
    EvmStateChangeErc1155ApprovalForAllFromJSON,
    EvmStateChangeErc1155ApprovalForAllFromJSONTyped,
    EvmStateChangeErc1155ApprovalForAllToJSON,
} from './EvmStateChangeErc1155ApprovalForAll';
import {
    EvmStateChangeErc1155Transfer,
    instanceOfEvmStateChangeErc1155Transfer,
    EvmStateChangeErc1155TransferFromJSON,
    EvmStateChangeErc1155TransferFromJSONTyped,
    EvmStateChangeErc1155TransferToJSON,
} from './EvmStateChangeErc1155Transfer';
import {
    EvmStateChangeErc20Approval,
    instanceOfEvmStateChangeErc20Approval,
    EvmStateChangeErc20ApprovalFromJSON,
    EvmStateChangeErc20ApprovalFromJSONTyped,
    EvmStateChangeErc20ApprovalToJSON,
} from './EvmStateChangeErc20Approval';
import {
    EvmStateChangeErc20Transfer,
    instanceOfEvmStateChangeErc20Transfer,
    EvmStateChangeErc20TransferFromJSON,
    EvmStateChangeErc20TransferFromJSONTyped,
    EvmStateChangeErc20TransferToJSON,
} from './EvmStateChangeErc20Transfer';
import {
    EvmStateChangeErc721Approval,
    instanceOfEvmStateChangeErc721Approval,
    EvmStateChangeErc721ApprovalFromJSON,
    EvmStateChangeErc721ApprovalFromJSONTyped,
    EvmStateChangeErc721ApprovalToJSON,
} from './EvmStateChangeErc721Approval';
import {
    EvmStateChangeErc721ApprovalForAll,
    instanceOfEvmStateChangeErc721ApprovalForAll,
    EvmStateChangeErc721ApprovalForAllFromJSON,
    EvmStateChangeErc721ApprovalForAllFromJSONTyped,
    EvmStateChangeErc721ApprovalForAllToJSON,
} from './EvmStateChangeErc721ApprovalForAll';
import {
    EvmStateChangeErc721Transfer,
    instanceOfEvmStateChangeErc721Transfer,
    EvmStateChangeErc721TransferFromJSON,
    EvmStateChangeErc721TransferFromJSONTyped,
    EvmStateChangeErc721TransferToJSON,
} from './EvmStateChangeErc721Transfer';
import {
    EvmStateChangeNativeAssetTransfer,
    instanceOfEvmStateChangeNativeAssetTransfer,
    EvmStateChangeNativeAssetTransferFromJSON,
    EvmStateChangeNativeAssetTransferFromJSONTyped,
    EvmStateChangeNativeAssetTransferToJSON,
} from './EvmStateChangeNativeAssetTransfer';

/**
 * @type ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo
 * A machine-parsable state change object describing the state change.
 * @export
 */
export type ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo = { kind: 'ERC1155_APPROVAL_FOR_ALL' } & EvmStateChangeErc1155ApprovalForAll | { kind: 'ERC1155_TRANSFER' } & EvmStateChangeErc1155Transfer | { kind: 'ERC20_APPROVAL' } & EvmStateChangeErc20Approval | { kind: 'ERC20_TRANSFER' } & EvmStateChangeErc20Transfer | { kind: 'ERC721_APPROVAL' } & EvmStateChangeErc721Approval | { kind: 'ERC721_APPROVAL_FOR_ALL' } & EvmStateChangeErc721ApprovalForAll | { kind: 'ERC721_TRANSFER' } & EvmStateChangeErc721Transfer | { kind: 'NATIVE_ASSET_TRANSFER' } & EvmStateChangeNativeAssetTransfer;

export function ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSON(json: any): ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo {
    return ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSONTyped(json, false);
}

export function ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['kind']) {
        case 'ERC1155_APPROVAL_FOR_ALL':
            return {...EvmStateChangeErc1155ApprovalForAllFromJSONTyped(json, true), kind: 'ERC1155_APPROVAL_FOR_ALL'};
        case 'ERC1155_TRANSFER':
            return {...EvmStateChangeErc1155TransferFromJSONTyped(json, true), kind: 'ERC1155_TRANSFER'};
        case 'ERC20_APPROVAL':
            return {...EvmStateChangeErc20ApprovalFromJSONTyped(json, true), kind: 'ERC20_APPROVAL'};
        case 'ERC20_TRANSFER':
            return {...EvmStateChangeErc20TransferFromJSONTyped(json, true), kind: 'ERC20_TRANSFER'};
        case 'ERC721_APPROVAL':
            return {...EvmStateChangeErc721ApprovalFromJSONTyped(json, true), kind: 'ERC721_APPROVAL'};
        case 'ERC721_APPROVAL_FOR_ALL':
            return {...EvmStateChangeErc721ApprovalForAllFromJSONTyped(json, true), kind: 'ERC721_APPROVAL_FOR_ALL'};
        case 'ERC721_TRANSFER':
            return {...EvmStateChangeErc721TransferFromJSONTyped(json, true), kind: 'ERC721_TRANSFER'};
        case 'NATIVE_ASSET_TRANSFER':
            return {...EvmStateChangeNativeAssetTransferFromJSONTyped(json, true), kind: 'NATIVE_ASSET_TRANSFER'};
        default:
            throw new Error(`No variant of ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo exists with 'kind=${json['kind']}'`);
    }
}

export function ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoToJSON(value?: ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['kind']) {
        case 'ERC1155_APPROVAL_FOR_ALL':
            return EvmStateChangeErc1155ApprovalForAllToJSON(value);
        case 'ERC1155_TRANSFER':
            return EvmStateChangeErc1155TransferToJSON(value);
        case 'ERC20_APPROVAL':
            return EvmStateChangeErc20ApprovalToJSON(value);
        case 'ERC20_TRANSFER':
            return EvmStateChangeErc20TransferToJSON(value);
        case 'ERC721_APPROVAL':
            return EvmStateChangeErc721ApprovalToJSON(value);
        case 'ERC721_APPROVAL_FOR_ALL':
            return EvmStateChangeErc721ApprovalForAllToJSON(value);
        case 'ERC721_TRANSFER':
            return EvmStateChangeErc721TransferToJSON(value);
        case 'NATIVE_ASSET_TRANSFER':
            return EvmStateChangeNativeAssetTransferToJSON(value);
        default:
            throw new Error(`No variant of ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo exists with 'kind=${value['kind']}'`);
    }

}

