/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo } from './ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo';
import {
    ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSON,
    ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSONTyped,
    ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoToJSON,
} from './ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo';

/**
 * 
 * @export
 * @interface ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInner
 */
export interface ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInner {
    /**
     * Computed explanation of the state change that can be directly presented to the end-user. While the API is still in development, we suggest integrators expose this in their signing UI if they encounter a `rawInfo.kind` they don't recognize.
     * @type {string}
     * @memberof ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInner
     */
    humanReadableDiff: string;
    /**
     * 
     * @type {ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo}
     * @memberof ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInner
     */
    rawInfo: ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo;
}

/**
 * Check if a given object implements the ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInner interface.
 */
export function instanceOfScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "humanReadableDiff" in value;
    isInstance = isInstance && "rawInfo" in value;

    return isInstance;
}

export function ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerFromJSON(json: any): ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInner {
    return ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerFromJSONTyped(json, false);
}

export function ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'humanReadableDiff': json['humanReadableDiff'],
        'rawInfo': ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSON(json['rawInfo']),
    };
}

export function ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerToJSON(value?: ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'humanReadableDiff': value.humanReadableDiff,
        'rawInfo': ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoToJSON(value.rawInfo),
    };
}

