/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOf
 */
export interface ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOf {
    /**
     * 
     * @type {number}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOf
     */
    lamports: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOf
     */
    data: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOf
     */
    owner: string;
    /**
     * 
     * @type {boolean}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOf
     */
    executable: boolean;
    /**
     * 
     * @type {number}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOf
     */
    rentEpoch: number;
}

/**
 * Check if a given object implements the ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOf interface.
 */
export function instanceOfScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lamports" in value;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "owner" in value;
    isInstance = isInstance && "executable" in value;
    isInstance = isInstance && "rentEpoch" in value;

    return isInstance;
}

export function ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOfFromJSON(json: any): ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOf {
    return ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOfFromJSONTyped(json, false);
}

export function ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lamports': json['lamports'],
        'data': json['data'],
        'owner': json['owner'],
        'executable': json['executable'],
        'rentEpoch': json['rentEpoch'],
    };
}

export function ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOfToJSON(value?: ScanTransactionsSolana200ResponseSimulationResultsRawAccountsInnerAnyOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lamports': value.lamports,
        'data': value.data,
        'owner': value.owner,
        'executable': value.executable,
        'rentEpoch': value.rentEpoch,
    };
}

