/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmTxData } from './EvmTxData';
import {
    EvmTxDataFromJSON,
    EvmTxDataFromJSONTyped,
    EvmTxDataToJSON,
} from './EvmTxData';
import type { RequestMetadata } from './RequestMetadata';
import {
    RequestMetadataFromJSON,
    RequestMetadataFromJSONTyped,
    RequestMetadataToJSON,
} from './RequestMetadata';

/**
 * 
 * @export
 * @interface ScanTransactionEvmRequest
 */
export interface ScanTransactionEvmRequest {
    /**
     * 
     * @type {EvmTxData}
     * @memberof ScanTransactionEvmRequest
     */
    txObject: EvmTxData;
    /**
     * 
     * @type {RequestMetadata}
     * @memberof ScanTransactionEvmRequest
     */
    metadata: RequestMetadata;
    /**
     * A hex-representation of the user account who is being asked to sign the supplied transaction. In most cases this will be the same as the from property in the txObject
     * @type {string}
     * @memberof ScanTransactionEvmRequest
     */
    userAccount: string;
}

/**
 * Check if a given object implements the ScanTransactionEvmRequest interface.
 */
export function instanceOfScanTransactionEvmRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "txObject" in value;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "userAccount" in value;

    return isInstance;
}

export function ScanTransactionEvmRequestFromJSON(json: any): ScanTransactionEvmRequest {
    return ScanTransactionEvmRequestFromJSONTyped(json, false);
}

export function ScanTransactionEvmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionEvmRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'txObject': EvmTxDataFromJSON(json['txObject']),
        'metadata': RequestMetadataFromJSON(json['metadata']),
        'userAccount': json['userAccount'],
    };
}

export function ScanTransactionEvmRequestToJSON(value?: ScanTransactionEvmRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'txObject': EvmTxDataToJSON(value.txObject),
        'metadata': RequestMetadataToJSON(value.metadata),
        'userAccount': value.userAccount,
    };
}

