/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Can be `null`.
 * @export
 * @interface ScanTransactionsSolana200ResponseSimulationResultsRawReturnData
 */
export interface ScanTransactionsSolana200ResponseSimulationResultsRawReturnData {
    /**
     * the program that generated the return data, as base-58 encoded Pubkey
     * @type {string}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsRawReturnData
     */
    programId: string;
    /**
     * The return data itself, as base-64 encoded binary data and it's encoding as the second element
     * @type {Array<string>}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsRawReturnData
     */
    data: Array<string>;
}

/**
 * Check if a given object implements the ScanTransactionsSolana200ResponseSimulationResultsRawReturnData interface.
 */
export function instanceOfScanTransactionsSolana200ResponseSimulationResultsRawReturnData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "programId" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function ScanTransactionsSolana200ResponseSimulationResultsRawReturnDataFromJSON(json: any): ScanTransactionsSolana200ResponseSimulationResultsRawReturnData {
    return ScanTransactionsSolana200ResponseSimulationResultsRawReturnDataFromJSONTyped(json, false);
}

export function ScanTransactionsSolana200ResponseSimulationResultsRawReturnDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionsSolana200ResponseSimulationResultsRawReturnData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'programId': json['programId'],
        'data': json['data'],
    };
}

export function ScanTransactionsSolana200ResponseSimulationResultsRawReturnDataToJSON(value?: ScanTransactionsSolana200ResponseSimulationResultsRawReturnData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'programId': value.programId,
        'data': value.data,
    };
}

