/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo } from './ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo';
import {
    ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSON,
    ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSONTyped,
    ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoToJSON,
} from './ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo';

/**
 * 
 * @export
 * @interface ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner
 */
export interface ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner {
    /**
     * Computed explanation of the state change that can be directly presented to the end-user. While the API is still in development, we suggest integrators expose this in their signing UI if they encounter a `rawInfo.kind` they don't recognize.
     * @type {string}
     * @memberof ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner
     */
    humanReadableDiff: string;
    /**
     * 
     * @type {ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo}
     * @memberof ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner
     */
    rawInfo: ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo;
}

/**
 * Check if a given object implements the ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner interface.
 */
export function instanceOfScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "humanReadableDiff" in value;
    isInstance = isInstance && "rawInfo" in value;

    return isInstance;
}

export function ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerFromJSON(json: any): ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner {
    return ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerFromJSONTyped(json, false);
}

export function ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'humanReadableDiff': json['humanReadableDiff'],
        'rawInfo': ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSON(json['rawInfo']),
    };
}

export function ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerToJSON(value?: ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'humanReadableDiff': value.humanReadableDiff,
        'rawInfo': ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoToJSON(value.rawInfo),
    };
}

