/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EvmSimulationFailedError,
    instanceOfEvmSimulationFailedError,
    EvmSimulationFailedErrorFromJSON,
    EvmSimulationFailedErrorFromJSONTyped,
    EvmSimulationFailedErrorToJSON,
} from './EvmSimulationFailedError';
import {
    EvmUnknownError,
    instanceOfEvmUnknownError,
    EvmUnknownErrorFromJSON,
    EvmUnknownErrorFromJSONTyped,
    EvmUnknownErrorToJSON,
} from './EvmUnknownError';

/**
 * @type ScanTransactionsEvm200ResponseSimulationResultsAggregatedError
 * A error object which includes the aggregated parsed simulation error encountered (if any). Can be `null`.
 * @export
 */
export type ScanTransactionsEvm200ResponseSimulationResultsAggregatedError = { kind: 'SIMULATION_FAILED' } & EvmSimulationFailedError | { kind: 'UNKNOWN_ERROR' } & EvmUnknownError;

export function ScanTransactionsEvm200ResponseSimulationResultsAggregatedErrorFromJSON(json: any): ScanTransactionsEvm200ResponseSimulationResultsAggregatedError {
    return ScanTransactionsEvm200ResponseSimulationResultsAggregatedErrorFromJSONTyped(json, false);
}

export function ScanTransactionsEvm200ResponseSimulationResultsAggregatedErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionsEvm200ResponseSimulationResultsAggregatedError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['kind']) {
        case 'SIMULATION_FAILED':
            return {...EvmSimulationFailedErrorFromJSONTyped(json, true), kind: 'SIMULATION_FAILED'};
        case 'UNKNOWN_ERROR':
            return {...EvmUnknownErrorFromJSONTyped(json, true), kind: 'UNKNOWN_ERROR'};
        default:
            throw new Error(`No variant of ScanTransactionsEvm200ResponseSimulationResultsAggregatedError exists with 'kind=${json['kind']}'`);
    }
}

export function ScanTransactionsEvm200ResponseSimulationResultsAggregatedErrorToJSON(value?: ScanTransactionsEvm200ResponseSimulationResultsAggregatedError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['kind']) {
        case 'SIMULATION_FAILED':
            return EvmSimulationFailedErrorToJSON(value);
        case 'UNKNOWN_ERROR':
            return EvmUnknownErrorToJSON(value);
        default:
            throw new Error(`No variant of ScanTransactionsEvm200ResponseSimulationResultsAggregatedError exists with 'kind=${value['kind']}'`);
    }

}

