/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An object that contains nullable fields with information about the estimated gas consumption of the simulated transaction
 * @export
 * @interface ScanTransactionEvm200ResponseSimulationResultsGas
 */
export interface ScanTransactionEvm200ResponseSimulationResultsGas {
    /**
     * A field that if the simulation was successful contains the estimated upper limit of gas usage for this transaction. The gasLimit should be viewed as an upper bound of how much gas the transaction can use, not as an accurate estimate how much it will realistically consume when submitted on-chain. Can be `null`.
     * @type {string}
     * @memberof ScanTransactionEvm200ResponseSimulationResultsGas
     */
    gasLimit: string | null;
}

/**
 * Check if a given object implements the ScanTransactionEvm200ResponseSimulationResultsGas interface.
 */
export function instanceOfScanTransactionEvm200ResponseSimulationResultsGas(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "gasLimit" in value;

    return isInstance;
}

export function ScanTransactionEvm200ResponseSimulationResultsGasFromJSON(json: any): ScanTransactionEvm200ResponseSimulationResultsGas {
    return ScanTransactionEvm200ResponseSimulationResultsGasFromJSONTyped(json, false);
}

export function ScanTransactionEvm200ResponseSimulationResultsGasFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionEvm200ResponseSimulationResultsGas {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gasLimit': json['gasLimit'],
    };
}

export function ScanTransactionEvm200ResponseSimulationResultsGasToJSON(value?: ScanTransactionEvm200ResponseSimulationResultsGas | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gasLimit': value.gasLimit,
    };
}

