/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfo } from './ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfo';
import {
    ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSON,
    ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSONTyped,
    ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfoToJSON,
} from './ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfo';

/**
 * 
 * @export
 * @interface ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInner
 */
export interface ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInner {
    /**
     * Computed explanation of the state change that can be directly presented to the end-user. While the API is still in development, we suggest integrators expose this in their signing UI since the list of state change kinds has not yet stabilized.
     * @type {string}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInner
     */
    humanReadableDiff: string;
    /**
     * Suggested text color when presenting the diff to end-users
     * @type {string}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInner
     */
    suggestedColor: ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerSuggestedColorEnum;
    /**
     * 
     * @type {ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfo}
     * @memberof ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInner
     */
    rawInfo: ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfo;
}


/**
 * @export
 */
export const ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerSuggestedColorEnum = {
    Credit: 'CREDIT',
    Debit: 'DEBIT'
} as const;
export type ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerSuggestedColorEnum = typeof ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerSuggestedColorEnum[keyof typeof ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerSuggestedColorEnum];


/**
 * Check if a given object implements the ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInner interface.
 */
export function instanceOfScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "humanReadableDiff" in value;
    isInstance = isInstance && "suggestedColor" in value;
    isInstance = isInstance && "rawInfo" in value;

    return isInstance;
}

export function ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerFromJSON(json: any): ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInner {
    return ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerFromJSONTyped(json, false);
}

export function ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'humanReadableDiff': json['humanReadableDiff'],
        'suggestedColor': json['suggestedColor'],
        'rawInfo': ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSON(json['rawInfo']),
    };
}

export function ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerToJSON(value?: ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'humanReadableDiff': value.humanReadableDiff,
        'suggestedColor': value.suggestedColor,
        'rawInfo': ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfoToJSON(value.rawInfo),
    };
}

