/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError } from './ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError';
import {
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorFromJSON,
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorFromJSONTyped,
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorToJSON,
} from './ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError';
import type { ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas } from './ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas';
import {
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasFromJSON,
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasFromJSONTyped,
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasToJSON,
} from './ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas';

/**
 * 
 * @export
 * @interface ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner
 */
export interface ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner {
    /**
     * 
     * @type {ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError}
     * @memberof ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner
     */
    error: ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError | null;
    /**
     * 
     * @type {ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas}
     * @memberof ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner
     */
    gas: ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas;
}

/**
 * Check if a given object implements the ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner interface.
 */
export function instanceOfScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "error" in value;
    isInstance = isInstance && "gas" in value;

    return isInstance;
}

export function ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerFromJSON(json: any): ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner {
    return ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerFromJSONTyped(json, false);
}

export function ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorFromJSON(json['error']),
        'gas': ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasFromJSON(json['gas']),
    };
}

export function ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerToJSON(value?: ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorToJSON(value.error),
        'gas': ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasToJSON(value.gas),
    };
}

