/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    SolanaStageChangeSplTransfer,
    instanceOfSolanaStageChangeSplTransfer,
    SolanaStageChangeSplTransferFromJSON,
    SolanaStageChangeSplTransferFromJSONTyped,
    SolanaStageChangeSplTransferToJSON,
} from './SolanaStageChangeSplTransfer';
import {
    SolanaStateChangeSolStakeAuthorityChange,
    instanceOfSolanaStateChangeSolStakeAuthorityChange,
    SolanaStateChangeSolStakeAuthorityChangeFromJSON,
    SolanaStateChangeSolStakeAuthorityChangeFromJSONTyped,
    SolanaStateChangeSolStakeAuthorityChangeToJSON,
} from './SolanaStateChangeSolStakeAuthorityChange';
import {
    SolanaStateChangeSolTransfer,
    instanceOfSolanaStateChangeSolTransfer,
    SolanaStateChangeSolTransferFromJSON,
    SolanaStateChangeSolTransferFromJSONTyped,
    SolanaStateChangeSolTransferToJSON,
} from './SolanaStateChangeSolTransfer';
import {
    SolanaStateChangeSplApproval,
    instanceOfSolanaStateChangeSplApproval,
    SolanaStateChangeSplApprovalFromJSON,
    SolanaStateChangeSplApprovalFromJSONTyped,
    SolanaStateChangeSplApprovalToJSON,
} from './SolanaStateChangeSplApproval';

/**
 * @type ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfo
 * A machine-parsable state change object describing the state change.
 * @export
 */
export type ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfo = { kind: 'SOL_STAKE_AUTHORITY_CHANGE' } & SolanaStateChangeSolStakeAuthorityChange | { kind: 'SOL_TRANSFER' } & SolanaStateChangeSolTransfer | { kind: 'SPL_APPROVAL' } & SolanaStateChangeSplApproval | { kind: 'SPL_TRANSFER' } & SolanaStageChangeSplTransfer;

export function ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSON(json: any): ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfo {
    return ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSONTyped(json, false);
}

export function ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['kind']) {
        case 'SOL_STAKE_AUTHORITY_CHANGE':
            return {...SolanaStateChangeSolStakeAuthorityChangeFromJSONTyped(json, true), kind: 'SOL_STAKE_AUTHORITY_CHANGE'};
        case 'SOL_TRANSFER':
            return {...SolanaStateChangeSolTransferFromJSONTyped(json, true), kind: 'SOL_TRANSFER'};
        case 'SPL_APPROVAL':
            return {...SolanaStateChangeSplApprovalFromJSONTyped(json, true), kind: 'SPL_APPROVAL'};
        case 'SPL_TRANSFER':
            return {...SolanaStageChangeSplTransferFromJSONTyped(json, true), kind: 'SPL_TRANSFER'};
        default:
            throw new Error(`No variant of ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfo exists with 'kind=${json['kind']}'`);
    }
}

export function ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfoToJSON(value?: ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['kind']) {
        case 'SOL_STAKE_AUTHORITY_CHANGE':
            return SolanaStateChangeSolStakeAuthorityChangeToJSON(value);
        case 'SOL_TRANSFER':
            return SolanaStateChangeSolTransferToJSON(value);
        case 'SPL_APPROVAL':
            return SolanaStateChangeSplApprovalToJSON(value);
        case 'SPL_TRANSFER':
            return SolanaStageChangeSplTransferToJSON(value);
        default:
            throw new Error(`No variant of ScanTransactionsSolana200ResponseSimulationResultsExpectedStateChangesInnerRawInfo exists with 'kind=${value['kind']}'`);
    }

}

