/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EvmSimulationFailedError,
    instanceOfEvmSimulationFailedError,
    EvmSimulationFailedErrorFromJSON,
    EvmSimulationFailedErrorFromJSONTyped,
    EvmSimulationFailedErrorToJSON,
} from './EvmSimulationFailedError';
import {
    EvmTransactionError,
    instanceOfEvmTransactionError,
    EvmTransactionErrorFromJSON,
    EvmTransactionErrorFromJSONTyped,
    EvmTransactionErrorToJSON,
} from './EvmTransactionError';
import {
    EvmTransactionRevertedError,
    instanceOfEvmTransactionRevertedError,
    EvmTransactionRevertedErrorFromJSON,
    EvmTransactionRevertedErrorFromJSONTyped,
    EvmTransactionRevertedErrorToJSON,
} from './EvmTransactionRevertedError';
import {
    EvmUnknownError,
    instanceOfEvmUnknownError,
    EvmUnknownErrorFromJSON,
    EvmUnknownErrorFromJSONTyped,
    EvmUnknownErrorToJSON,
} from './EvmUnknownError';

/**
 * @type ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError
 * A error object which includes the parsed simulation error encountered (if any). Can be `null`.
 * @export
 */
export type ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError = { kind: 'SIMULATION_FAILED' } & EvmSimulationFailedError | { kind: 'TRANSACTION_ERROR' } & EvmTransactionError | { kind: 'TRANSACTION_REVERTED' } & EvmTransactionRevertedError | { kind: 'UNKNOWN_ERROR' } & EvmUnknownError;

export function ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorFromJSON(json: any): ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError {
    return ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorFromJSONTyped(json, false);
}

export function ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['kind']) {
        case 'SIMULATION_FAILED':
            return {...EvmSimulationFailedErrorFromJSONTyped(json, true), kind: 'SIMULATION_FAILED'};
        case 'TRANSACTION_ERROR':
            return {...EvmTransactionErrorFromJSONTyped(json, true), kind: 'TRANSACTION_ERROR'};
        case 'TRANSACTION_REVERTED':
            return {...EvmTransactionRevertedErrorFromJSONTyped(json, true), kind: 'TRANSACTION_REVERTED'};
        case 'UNKNOWN_ERROR':
            return {...EvmUnknownErrorFromJSONTyped(json, true), kind: 'UNKNOWN_ERROR'};
        default:
            throw new Error(`No variant of ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError exists with 'kind=${json['kind']}'`);
    }
}

export function ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorToJSON(value?: ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['kind']) {
        case 'SIMULATION_FAILED':
            return EvmSimulationFailedErrorToJSON(value);
        case 'TRANSACTION_ERROR':
            return EvmTransactionErrorToJSON(value);
        case 'TRANSACTION_REVERTED':
            return EvmTransactionRevertedErrorToJSON(value);
        case 'UNKNOWN_ERROR':
            return EvmUnknownErrorToJSON(value);
        default:
            throw new Error(`No variant of ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError exists with 'kind=${value['kind']}'`);
    }

}

