/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestMetadata } from './RequestMetadata';
import {
    RequestMetadataFromJSON,
    RequestMetadataFromJSONTyped,
    RequestMetadataToJSON,
} from './RequestMetadata';
import type { ScanMessageEvmRequestMessage } from './ScanMessageEvmRequestMessage';
import {
    ScanMessageEvmRequestMessageFromJSON,
    ScanMessageEvmRequestMessageFromJSONTyped,
    ScanMessageEvmRequestMessageToJSON,
} from './ScanMessageEvmRequestMessage';

/**
 * 
 * @export
 * @interface ScanMessageEvmRequest
 */
export interface ScanMessageEvmRequest {
    /**
     * 
     * @type {ScanMessageEvmRequestMessage}
     * @memberof ScanMessageEvmRequest
     */
    message: ScanMessageEvmRequestMessage;
    /**
     * 
     * @type {RequestMetadata}
     * @memberof ScanMessageEvmRequest
     */
    metadata: RequestMetadata;
    /**
     * A hex-representation of the user account who is being asked to sign the supplied transaction. In most cases this will be the same as the from property in the txObject
     * @type {string}
     * @memberof ScanMessageEvmRequest
     */
    userAccount: string;
}

/**
 * Check if a given object implements the ScanMessageEvmRequest interface.
 */
export function instanceOfScanMessageEvmRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "userAccount" in value;

    return isInstance;
}

export function ScanMessageEvmRequestFromJSON(json: any): ScanMessageEvmRequest {
    return ScanMessageEvmRequestFromJSONTyped(json, false);
}

export function ScanMessageEvmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanMessageEvmRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': ScanMessageEvmRequestMessageFromJSON(json['message']),
        'metadata': RequestMetadataFromJSON(json['metadata']),
        'userAccount': json['userAccount'],
    };
}

export function ScanMessageEvmRequestToJSON(value?: ScanMessageEvmRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': ScanMessageEvmRequestMessageToJSON(value.message),
        'metadata': RequestMetadataToJSON(value.metadata),
        'userAccount': value.userAccount,
    };
}

