/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ActionEnum } from './ActionEnum';
import {
    ActionEnumFromJSON,
    ActionEnumFromJSONTyped,
    ActionEnumToJSON,
} from './ActionEnum';
import type { ScanMessageEvm200ResponseSimulationResults } from './ScanMessageEvm200ResponseSimulationResults';
import {
    ScanMessageEvm200ResponseSimulationResultsFromJSON,
    ScanMessageEvm200ResponseSimulationResultsFromJSONTyped,
    ScanMessageEvm200ResponseSimulationResultsToJSON,
} from './ScanMessageEvm200ResponseSimulationResults';
import type { WarningInner } from './WarningInner';
import {
    WarningInnerFromJSON,
    WarningInnerFromJSONTyped,
    WarningInnerToJSON,
} from './WarningInner';

/**
 * 
 * @export
 * @interface ScanMessageEvm200Response
 */
export interface ScanMessageEvm200Response {
    /**
     * 
     * @type {ActionEnum}
     * @memberof ScanMessageEvm200Response
     */
    action: ActionEnum;
    /**
     * An array of warnings generated from scanning the transactions. All these warnings won't be returned in a single response (some are mutually exclusive) but it is advisable that your UI can display multiple warnings. Warnings are returned sorted by severity, so if you can only show a user one warning, show them the one at the 0th index.
     * @type {Array<WarningInner>}
     * @memberof ScanMessageEvm200Response
     */
    warnings: Array<WarningInner>;
    /**
     * 
     * @type {ScanMessageEvm200ResponseSimulationResults}
     * @memberof ScanMessageEvm200Response
     */
    simulationResults: ScanMessageEvm200ResponseSimulationResults | null;
}

/**
 * Check if a given object implements the ScanMessageEvm200Response interface.
 */
export function instanceOfScanMessageEvm200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "warnings" in value;
    isInstance = isInstance && "simulationResults" in value;

    return isInstance;
}

export function ScanMessageEvm200ResponseFromJSON(json: any): ScanMessageEvm200Response {
    return ScanMessageEvm200ResponseFromJSONTyped(json, false);
}

export function ScanMessageEvm200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanMessageEvm200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': ActionEnumFromJSON(json['action']),
        'warnings': ((json['warnings'] as Array<any>).map(WarningInnerFromJSON)),
        'simulationResults': ScanMessageEvm200ResponseSimulationResultsFromJSON(json['simulationResults']),
    };
}

export function ScanMessageEvm200ResponseToJSON(value?: ScanMessageEvm200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': ActionEnumToJSON(value.action),
        'warnings': ((value.warnings as Array<any>).map(WarningInnerToJSON)),
        'simulationResults': ScanMessageEvm200ResponseSimulationResultsToJSON(value.simulationResults),
    };
}

