/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScanTransactionsEvm200ResponseSimulationResultsAggregated } from './ScanTransactionsEvm200ResponseSimulationResultsAggregated';
import {
    ScanTransactionsEvm200ResponseSimulationResultsAggregatedFromJSON,
    ScanTransactionsEvm200ResponseSimulationResultsAggregatedFromJSONTyped,
    ScanTransactionsEvm200ResponseSimulationResultsAggregatedToJSON,
} from './ScanTransactionsEvm200ResponseSimulationResultsAggregated';
import type { ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner } from './ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner';
import {
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerFromJSON,
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerFromJSONTyped,
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerToJSON,
} from './ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner';

/**
 * 
 * @export
 * @interface ScanTransactionsEvm200ResponseSimulationResults
 */
export interface ScanTransactionsEvm200ResponseSimulationResults {
    /**
     * 
     * @type {ScanTransactionsEvm200ResponseSimulationResultsAggregated}
     * @memberof ScanTransactionsEvm200ResponseSimulationResults
     */
    aggregated: ScanTransactionsEvm200ResponseSimulationResultsAggregated;
    /**
     * 
     * @type {Array<ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner>}
     * @memberof ScanTransactionsEvm200ResponseSimulationResults
     */
    perTransaction: Array<ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInner>;
}

/**
 * Check if a given object implements the ScanTransactionsEvm200ResponseSimulationResults interface.
 */
export function instanceOfScanTransactionsEvm200ResponseSimulationResults(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "aggregated" in value;
    isInstance = isInstance && "perTransaction" in value;

    return isInstance;
}

export function ScanTransactionsEvm200ResponseSimulationResultsFromJSON(json: any): ScanTransactionsEvm200ResponseSimulationResults {
    return ScanTransactionsEvm200ResponseSimulationResultsFromJSONTyped(json, false);
}

export function ScanTransactionsEvm200ResponseSimulationResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionsEvm200ResponseSimulationResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aggregated': ScanTransactionsEvm200ResponseSimulationResultsAggregatedFromJSON(json['aggregated']),
        'perTransaction': ((json['perTransaction'] as Array<any>).map(ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerFromJSON)),
    };
}

export function ScanTransactionsEvm200ResponseSimulationResultsToJSON(value?: ScanTransactionsEvm200ResponseSimulationResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aggregated': ScanTransactionsEvm200ResponseSimulationResultsAggregatedToJSON(value.aggregated),
        'perTransaction': ((value.perTransaction as Array<any>).map(ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerToJSON)),
    };
}

