/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScanTransactionEvm200ResponseSimulationResultsError } from './ScanTransactionEvm200ResponseSimulationResultsError';
import {
    ScanTransactionEvm200ResponseSimulationResultsErrorFromJSON,
    ScanTransactionEvm200ResponseSimulationResultsErrorFromJSONTyped,
    ScanTransactionEvm200ResponseSimulationResultsErrorToJSON,
} from './ScanTransactionEvm200ResponseSimulationResultsError';
import type { ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner } from './ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner';
import {
    ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerFromJSON,
    ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerFromJSONTyped,
    ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerToJSON,
} from './ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner';
import type { ScanTransactionEvm200ResponseSimulationResultsGas } from './ScanTransactionEvm200ResponseSimulationResultsGas';
import {
    ScanTransactionEvm200ResponseSimulationResultsGasFromJSON,
    ScanTransactionEvm200ResponseSimulationResultsGasFromJSONTyped,
    ScanTransactionEvm200ResponseSimulationResultsGasToJSON,
} from './ScanTransactionEvm200ResponseSimulationResultsGas';

/**
 * 
 * @export
 * @interface ScanTransactionEvm200ResponseSimulationResults
 */
export interface ScanTransactionEvm200ResponseSimulationResults {
    /**
     * 
     * @type {Array<ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner>}
     * @memberof ScanTransactionEvm200ResponseSimulationResults
     */
    expectedStateChanges: Array<ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInner>;
    /**
     * 
     * @type {ScanTransactionEvm200ResponseSimulationResultsError}
     * @memberof ScanTransactionEvm200ResponseSimulationResults
     */
    error: ScanTransactionEvm200ResponseSimulationResultsError | null;
    /**
     * 
     * @type {ScanTransactionEvm200ResponseSimulationResultsGas}
     * @memberof ScanTransactionEvm200ResponseSimulationResults
     */
    gas: ScanTransactionEvm200ResponseSimulationResultsGas;
}

/**
 * Check if a given object implements the ScanTransactionEvm200ResponseSimulationResults interface.
 */
export function instanceOfScanTransactionEvm200ResponseSimulationResults(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "expectedStateChanges" in value;
    isInstance = isInstance && "error" in value;
    isInstance = isInstance && "gas" in value;

    return isInstance;
}

export function ScanTransactionEvm200ResponseSimulationResultsFromJSON(json: any): ScanTransactionEvm200ResponseSimulationResults {
    return ScanTransactionEvm200ResponseSimulationResultsFromJSONTyped(json, false);
}

export function ScanTransactionEvm200ResponseSimulationResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionEvm200ResponseSimulationResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expectedStateChanges': ((json['expectedStateChanges'] as Array<any>).map(ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerFromJSON)),
        'error': ScanTransactionEvm200ResponseSimulationResultsErrorFromJSON(json['error']),
        'gas': ScanTransactionEvm200ResponseSimulationResultsGasFromJSON(json['gas']),
    };
}

export function ScanTransactionEvm200ResponseSimulationResultsToJSON(value?: ScanTransactionEvm200ResponseSimulationResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expectedStateChanges': ((value.expectedStateChanges as Array<any>).map(ScanTransactionEvm200ResponseSimulationResultsExpectedStateChangesInnerToJSON)),
        'error': ScanTransactionEvm200ResponseSimulationResultsErrorToJSON(value.error),
        'gas': ScanTransactionEvm200ResponseSimulationResultsGasToJSON(value.gas),
    };
}

