/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmExpectedStateChangesInner } from './EvmExpectedStateChangesInner';
import {
    EvmExpectedStateChangesInnerFromJSON,
    EvmExpectedStateChangesInnerFromJSONTyped,
    EvmExpectedStateChangesInnerToJSON,
} from './EvmExpectedStateChangesInner';
import type { ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError } from './ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError';
import {
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorFromJSON,
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorFromJSONTyped,
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorToJSON,
} from './ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError';
import type { ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas } from './ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas';
import {
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasFromJSON,
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasFromJSONTyped,
    ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasToJSON,
} from './ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas';

/**
 * 
 * @export
 * @interface ScanTransactionEvm200ResponseSimulationResults
 */
export interface ScanTransactionEvm200ResponseSimulationResults {
    /**
     * 
     * @type {Array<EvmExpectedStateChangesInner>}
     * @memberof ScanTransactionEvm200ResponseSimulationResults
     */
    expectedStateChanges: Array<EvmExpectedStateChangesInner>;
    /**
     * 
     * @type {ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError}
     * @memberof ScanTransactionEvm200ResponseSimulationResults
     */
    error: ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerError | null;
    /**
     * 
     * @type {ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas}
     * @memberof ScanTransactionEvm200ResponseSimulationResults
     */
    gas: ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGas;
}

/**
 * Check if a given object implements the ScanTransactionEvm200ResponseSimulationResults interface.
 */
export function instanceOfScanTransactionEvm200ResponseSimulationResults(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "expectedStateChanges" in value;
    isInstance = isInstance && "error" in value;
    isInstance = isInstance && "gas" in value;

    return isInstance;
}

export function ScanTransactionEvm200ResponseSimulationResultsFromJSON(json: any): ScanTransactionEvm200ResponseSimulationResults {
    return ScanTransactionEvm200ResponseSimulationResultsFromJSONTyped(json, false);
}

export function ScanTransactionEvm200ResponseSimulationResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTransactionEvm200ResponseSimulationResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expectedStateChanges': ((json['expectedStateChanges'] as Array<any>).map(EvmExpectedStateChangesInnerFromJSON)),
        'error': ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorFromJSON(json['error']),
        'gas': ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasFromJSON(json['gas']),
    };
}

export function ScanTransactionEvm200ResponseSimulationResultsToJSON(value?: ScanTransactionEvm200ResponseSimulationResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expectedStateChanges': ((value.expectedStateChanges as Array<any>).map(EvmExpectedStateChangesInnerToJSON)),
        'error': ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerErrorToJSON(value.error),
        'gas': ScanTransactionsEvm200ResponseSimulationResultsPerTransactionInnerGasToJSON(value.gas),
    };
}

