/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EvmStateChangeErc1155Transfer,
    instanceOfEvmStateChangeErc1155Transfer,
    EvmStateChangeErc1155TransferFromJSON,
    EvmStateChangeErc1155TransferFromJSONTyped,
    EvmStateChangeErc1155TransferToJSON,
} from './EvmStateChangeErc1155Transfer';
import {
    EvmStateChangeErc20Permit,
    instanceOfEvmStateChangeErc20Permit,
    EvmStateChangeErc20PermitFromJSON,
    EvmStateChangeErc20PermitFromJSONTyped,
    EvmStateChangeErc20PermitToJSON,
} from './EvmStateChangeErc20Permit';
import {
    EvmStateChangeErc20Transfer,
    instanceOfEvmStateChangeErc20Transfer,
    EvmStateChangeErc20TransferFromJSON,
    EvmStateChangeErc20TransferFromJSONTyped,
    EvmStateChangeErc20TransferToJSON,
} from './EvmStateChangeErc20Transfer';
import {
    EvmStateChangeErc721Transfer,
    instanceOfEvmStateChangeErc721Transfer,
    EvmStateChangeErc721TransferFromJSON,
    EvmStateChangeErc721TransferFromJSONTyped,
    EvmStateChangeErc721TransferToJSON,
} from './EvmStateChangeErc721Transfer';
import {
    EvmStateChangeNativeAssetTransfer,
    instanceOfEvmStateChangeNativeAssetTransfer,
    EvmStateChangeNativeAssetTransferFromJSON,
    EvmStateChangeNativeAssetTransferFromJSONTyped,
    EvmStateChangeNativeAssetTransferToJSON,
} from './EvmStateChangeNativeAssetTransfer';

/**
 * @type ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo
 * A machine-parsable state change object describing the state change.
 * @export
 */
export type ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo = { kind: 'ERC1155_TRANSFER' } & EvmStateChangeErc1155Transfer | { kind: 'ERC20_PERMIT' } & EvmStateChangeErc20Permit | { kind: 'ERC20_TRANSFER' } & EvmStateChangeErc20Transfer | { kind: 'ERC721_TRANSFER' } & EvmStateChangeErc721Transfer | { kind: 'NATIVE_ASSET_TRANSFER' } & EvmStateChangeNativeAssetTransfer;

export function ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSON(json: any): ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo {
    return ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSONTyped(json, false);
}

export function ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['kind']) {
        case 'ERC1155_TRANSFER':
            return {...EvmStateChangeErc1155TransferFromJSONTyped(json, true), kind: 'ERC1155_TRANSFER'};
        case 'ERC20_PERMIT':
            return {...EvmStateChangeErc20PermitFromJSONTyped(json, true), kind: 'ERC20_PERMIT'};
        case 'ERC20_TRANSFER':
            return {...EvmStateChangeErc20TransferFromJSONTyped(json, true), kind: 'ERC20_TRANSFER'};
        case 'ERC721_TRANSFER':
            return {...EvmStateChangeErc721TransferFromJSONTyped(json, true), kind: 'ERC721_TRANSFER'};
        case 'NATIVE_ASSET_TRANSFER':
            return {...EvmStateChangeNativeAssetTransferFromJSONTyped(json, true), kind: 'NATIVE_ASSET_TRANSFER'};
        default:
            throw new Error(`No variant of ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo exists with 'kind=${json['kind']}'`);
    }
}

export function ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfoToJSON(value?: ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['kind']) {
        case 'ERC1155_TRANSFER':
            return EvmStateChangeErc1155TransferToJSON(value);
        case 'ERC20_PERMIT':
            return EvmStateChangeErc20PermitToJSON(value);
        case 'ERC20_TRANSFER':
            return EvmStateChangeErc20TransferToJSON(value);
        case 'ERC721_TRANSFER':
            return EvmStateChangeErc721TransferToJSON(value);
        case 'NATIVE_ASSET_TRANSFER':
            return EvmStateChangeNativeAssetTransferToJSON(value);
        default:
            throw new Error(`No variant of ScanMessageEvm200ResponseSimulationResultsExpectedStateChangesInnerRawInfo exists with 'kind=${value['kind']}'`);
    }

}

