/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SolanaStateChangeSolStakeAuthorityChangeData } from './SolanaStateChangeSolStakeAuthorityChangeData';
import {
    SolanaStateChangeSolStakeAuthorityChangeDataFromJSON,
    SolanaStateChangeSolStakeAuthorityChangeDataFromJSONTyped,
    SolanaStateChangeSolStakeAuthorityChangeDataToJSON,
} from './SolanaStateChangeSolStakeAuthorityChangeData';

/**
 * Transferring control over a user's SOL staking account
 * @export
 * @interface SolanaStateChangeSolStakeAuthorityChange
 */
export interface SolanaStateChangeSolStakeAuthorityChange {
    /**
     * What kind of state change this object is
     * @type {string}
     * @memberof SolanaStateChangeSolStakeAuthorityChange
     */
    kind: SolanaStateChangeSolStakeAuthorityChangeKindEnum;
    /**
     * 
     * @type {SolanaStateChangeSolStakeAuthorityChangeData}
     * @memberof SolanaStateChangeSolStakeAuthorityChange
     */
    data: SolanaStateChangeSolStakeAuthorityChangeData;
}


/**
 * @export
 */
export const SolanaStateChangeSolStakeAuthorityChangeKindEnum = {
    SolStakeAuthorityChange: 'SOL_STAKE_AUTHORITY_CHANGE'
} as const;
export type SolanaStateChangeSolStakeAuthorityChangeKindEnum = typeof SolanaStateChangeSolStakeAuthorityChangeKindEnum[keyof typeof SolanaStateChangeSolStakeAuthorityChangeKindEnum];


/**
 * Check if a given object implements the SolanaStateChangeSolStakeAuthorityChange interface.
 */
export function instanceOfSolanaStateChangeSolStakeAuthorityChange(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function SolanaStateChangeSolStakeAuthorityChangeFromJSON(json: any): SolanaStateChangeSolStakeAuthorityChange {
    return SolanaStateChangeSolStakeAuthorityChangeFromJSONTyped(json, false);
}

export function SolanaStateChangeSolStakeAuthorityChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolanaStateChangeSolStakeAuthorityChange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'data': SolanaStateChangeSolStakeAuthorityChangeDataFromJSON(json['data']),
    };
}

export function SolanaStateChangeSolStakeAuthorityChangeToJSON(value?: SolanaStateChangeSolStakeAuthorityChange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'data': SolanaStateChangeSolStakeAuthorityChangeDataToJSON(value.data),
    };
}

