/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Diff } from './Diff';
import {
    DiffFromJSON,
    DiffFromJSONTyped,
    DiffToJSON,
} from './Diff';

/**
 * Machine-parseable data relevant to this state change kind
 * @export
 * @interface SolanaStateChangeSolTransferData
 */
export interface SolanaStateChangeSolTransferData {
    /**
     * Symbol of the Solana native token
     * @type {string}
     * @memberof SolanaStateChangeSolTransferData
     */
    symbol: string;
    /**
     * Name of the Solana native token
     * @type {string}
     * @memberof SolanaStateChangeSolTransferData
     */
    name: string;
    /**
     * Decimals of the Solana native token
     * @type {number}
     * @memberof SolanaStateChangeSolTransferData
     */
    decimals: number;
    /**
     * 
     * @type {Diff}
     * @memberof SolanaStateChangeSolTransferData
     */
    diff: Diff;
}

/**
 * Check if a given object implements the SolanaStateChangeSolTransferData interface.
 */
export function instanceOfSolanaStateChangeSolTransferData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "symbol" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "decimals" in value;
    isInstance = isInstance && "diff" in value;

    return isInstance;
}

export function SolanaStateChangeSolTransferDataFromJSON(json: any): SolanaStateChangeSolTransferData {
    return SolanaStateChangeSolTransferDataFromJSONTyped(json, false);
}

export function SolanaStateChangeSolTransferDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolanaStateChangeSolTransferData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
        'name': json['name'],
        'decimals': json['decimals'],
        'diff': DiffFromJSON(json['diff']),
    };
}

export function SolanaStateChangeSolTransferDataToJSON(value?: SolanaStateChangeSolTransferData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'symbol': value.symbol,
        'name': value.name,
        'decimals': value.decimals,
        'diff': DiffToJSON(value.diff),
    };
}

