/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Future authorities who will have control over the staking account
 * @export
 * @interface SolanaStateChangeSolStakeAuthorityChangeDataFutureAuthorities
 */
export interface SolanaStateChangeSolStakeAuthorityChangeDataFutureAuthorities {
    /**
     * Authority who can make staking changes
     * @type {string}
     * @memberof SolanaStateChangeSolStakeAuthorityChangeDataFutureAuthorities
     */
    staker: string;
    /**
     * Authority who can withdraw the funds from the staking account
     * @type {string}
     * @memberof SolanaStateChangeSolStakeAuthorityChangeDataFutureAuthorities
     */
    withdrawer: string;
}

/**
 * Check if a given object implements the SolanaStateChangeSolStakeAuthorityChangeDataFutureAuthorities interface.
 */
export function instanceOfSolanaStateChangeSolStakeAuthorityChangeDataFutureAuthorities(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "staker" in value;
    isInstance = isInstance && "withdrawer" in value;

    return isInstance;
}

export function SolanaStateChangeSolStakeAuthorityChangeDataFutureAuthoritiesFromJSON(json: any): SolanaStateChangeSolStakeAuthorityChangeDataFutureAuthorities {
    return SolanaStateChangeSolStakeAuthorityChangeDataFutureAuthoritiesFromJSONTyped(json, false);
}

export function SolanaStateChangeSolStakeAuthorityChangeDataFutureAuthoritiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolanaStateChangeSolStakeAuthorityChangeDataFutureAuthorities {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'staker': json['staker'],
        'withdrawer': json['withdrawer'],
    };
}

export function SolanaStateChangeSolStakeAuthorityChangeDataFutureAuthoritiesToJSON(value?: SolanaStateChangeSolStakeAuthorityChangeDataFutureAuthorities | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'staker': value.staker,
        'withdrawer': value.withdrawer,
    };
}

