/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2022-06-01
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SolanaStageChangeSplTransferData } from './SolanaStageChangeSplTransferData';
import {
    SolanaStageChangeSplTransferDataFromJSON,
    SolanaStageChangeSplTransferDataFromJSONTyped,
    SolanaStageChangeSplTransferDataToJSON,
} from './SolanaStageChangeSplTransferData';

/**
 * SPL token transfer
 * @export
 * @interface SolanaStageChangeSplTransfer
 */
export interface SolanaStageChangeSplTransfer {
    /**
     * What kind of state change this object is
     * @type {string}
     * @memberof SolanaStageChangeSplTransfer
     */
    kind: SolanaStageChangeSplTransferKindEnum;
    /**
     * 
     * @type {SolanaStageChangeSplTransferData}
     * @memberof SolanaStageChangeSplTransfer
     */
    data: SolanaStageChangeSplTransferData;
}


/**
 * @export
 */
export const SolanaStageChangeSplTransferKindEnum = {
    SplTransfer: 'SPL_TRANSFER'
} as const;
export type SolanaStageChangeSplTransferKindEnum = typeof SolanaStageChangeSplTransferKindEnum[keyof typeof SolanaStageChangeSplTransferKindEnum];


/**
 * Check if a given object implements the SolanaStageChangeSplTransfer interface.
 */
export function instanceOfSolanaStageChangeSplTransfer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function SolanaStageChangeSplTransferFromJSON(json: any): SolanaStageChangeSplTransfer {
    return SolanaStageChangeSplTransferFromJSONTyped(json, false);
}

export function SolanaStageChangeSplTransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolanaStageChangeSplTransfer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'data': SolanaStageChangeSplTransferDataFromJSON(json['data']),
    };
}

export function SolanaStageChangeSplTransferToJSON(value?: SolanaStageChangeSplTransfer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'data': SolanaStageChangeSplTransferDataToJSON(value.data),
    };
}

