// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriceSource } from "./PriceSource";

export interface Price {
  source: PriceSource;
  last_updated_at: number;
  dollar_value_per_token: number | null;
}
