packages:
  # executable/launchable applications
  - 'apps/*'
  # all packages in subdirs of packages/ and components/
  - 'packages/*'
  # exclude packages that are inside test directories
  - '!**/e2e/**'
  - '!**/__tests__/**'
