packages:
  # executable/launchable applications
  - 'apps/*'
  # all packages in subdirs of packages/
  - 'packages/*'
  # exclude packages that are inside test directories
  - '!**/e2e/**'
  - '!**/__tests__/**'
  # exclude the backend since it is using yarn
  - '!apps/extension-backend'
