// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvmTransactionObject } from "./EvmTransactionObject";
import type { RequestMetadata } from "./RequestMetadata";

export interface EvmTransactionRequest {
  txObject: EvmTransactionObject;
  metadata: RequestMetadata;
  userAccount: string | null;
}
