/* tslint:disable */
/* eslint-disable */
/**
 * API reference
 * The Blowfish API reference specification
 *
 * The version of the OpenAPI document: 2023-05-17
 * Contact: contact@blowfish.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  BadRequest,
  InternalServerError,
  Languages,
  ScanTransactionEvm200Response,
  ScanTransactionEvmRequest,
  Unauthorized,
} from "../models";
import { ChainFamily, ChainNetwork } from "../../types";

export interface ScanTransactionEvmOperationRequest {
  xApiKey: string;
  xApiVersion: string;
  language?: Languages;
  contentType?: string;
  scanTransactionEvmRequest?: ScanTransactionEvmRequest;
  chainFamily: ChainFamily;
  chainNetwork: ChainNetwork;
}

/**
 *
 */
export class ScanTransactionApi extends runtime.BaseAPI {
  /**
   * Scan an EVM transaction in order to receive recommended actions, tailored warnings and human-readable simulation results explaining what the transaction will do. ### Supported networks | Network | Base URL | | --- | --- | | Ethereum Mainnet | https://api.blowfish.xyz/ethereum/v0/mainnet/scan/transaction | | Goerli Testnet | https://api.blowfish.xyz/ethereum/v0/goerli/scan/transaction | | Polygon Mainnet | https://api.blowfish.xyz/polygon/v0/mainnet/scan/transaction | | BNB Chain Mainnet | https://api.blowfish.xyz/bnb/v0/mainnet/scan/transaction | | Arbitrum One | https://api.blowfish.xyz/arbitrum/v0/one/scan/transaction | | Optimism Goerli Testnet | https://api.blowfish.xyz/optimism/v0/goerli/scan/transaction | Note:  All EVM endpoints are equivalent when it comes to functionality as well as request and response formats.
   * EVM
   */
  async scanTransactionEvmRaw(
    requestParameters: ScanTransactionEvmOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ScanTransactionEvm200Response>> {
    if (
      requestParameters.xApiKey === null ||
      requestParameters.xApiKey === undefined
    ) {
      throw new runtime.RequiredError(
        "xApiKey",
        "Required parameter requestParameters.xApiKey was null or undefined when calling scanTransactionEvm."
      );
    }

    if (
      requestParameters.xApiVersion === null ||
      requestParameters.xApiVersion === undefined
    ) {
      throw new runtime.RequiredError(
        "xApiVersion",
        "Required parameter requestParameters.xApiVersion was null or undefined when calling scanTransactionEvm."
      );
    }

    const queryParameters: any = {};

    if (requestParameters.language !== undefined) {
      queryParameters["language"] = requestParameters.language;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (
      requestParameters.xApiKey !== undefined &&
      requestParameters.xApiKey !== null
    ) {
      headerParameters["X-Api-Key"] = String(requestParameters.xApiKey);
    }

    if (
      requestParameters.xApiVersion !== undefined &&
      requestParameters.xApiVersion !== null
    ) {
      headerParameters["X-Api-Version"] = String(requestParameters.xApiVersion);
    }

    if (
      requestParameters.contentType !== undefined &&
      requestParameters.contentType !== null
    ) {
      headerParameters["Content-Type"] = String(requestParameters.contentType);
    }

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["X-Api-Key"] = this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
    }

    const response = await this.request(
      {
        path: `/${requestParameters.chainFamily}/v0/${requestParameters.chainNetwork}/scan/transaction`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters.scanTransactionEvmRequest,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Scan an EVM transaction in order to receive recommended actions, tailored warnings and human-readable simulation results explaining what the transaction will do. ### Supported networks | Network | Base URL | | --- | --- | | Ethereum Mainnet | https://api.blowfish.xyz/ethereum/v0/mainnet/scan/transaction | | Goerli Testnet | https://api.blowfish.xyz/ethereum/v0/goerli/scan/transaction | | Polygon Mainnet | https://api.blowfish.xyz/polygon/v0/mainnet/scan/transaction | | BNB Chain Mainnet | https://api.blowfish.xyz/bnb/v0/mainnet/scan/transaction | | Arbitrum One | https://api.blowfish.xyz/arbitrum/v0/one/scan/transaction | | Optimism Goerli Testnet | https://api.blowfish.xyz/optimism/v0/goerli/scan/transaction | Note:  All EVM endpoints are equivalent when it comes to functionality as well as request and response formats.
   * EVM
   */
  async scanTransactionEvm(
    requestParameters: ScanTransactionEvmOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ScanTransactionEvm200Response> {
    const response = await this.scanTransactionEvmRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
