export const IS_IMPERSONATION_AVAILABLE =
  process.env.PLASMO_PUBLIC_BLOWFISH_WALLET_IMPERSONATION_AVAILABLE === "true";

export const BLOWFISH_TRANSACTION_PORTAL_URL =
  process.env.PLASMO_PUBLIC_BLOWFISH_TRANSACTION_PORTAL_URL;

export const BLOWFISH_EXTENSION_VERSION =
  process.env.PLASMO_PUBLIC_EXTENSION_VERSION;
