export const IS_IMPERSONATION_AVAILABLE =
  process.env.PLASMO_PUBLIC_BLOWFISH_WALLET_IMPERSONATION_AVAILABLE === "true";

export const CUSTOM_PORTAL_URL_ENABLED =
  process.env.PLASMO_PUBLIC_BLOWFISH_WALLET_PORTAL_URL_OVERRIDE_ENABLED ===
  "true";

export const CLEAR_STORAGE_ENABLED =
  process.env.PLASMO_PUBLIC_BLOWFISH_CLEAR_STORAGE_ENABLED === "true";

export const BLOWFISH_TRANSACTION_PORTAL_URL = process.env
  .PLASMO_PUBLIC_BLOWFISH_TRANSACTION_PORTAL_URL as string;

export const BLOWFISH_EXTENSION_VERSION = process.env
  .PLASMO_PUBLIC_EXTENSION_VERSION as string;

export const BLOWFISH_API_BASE_URL = process.env
  .PLASMO_PUBLIC_BLOWFISH_API_BASE_URL as string;
