// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvmExpectedStateChange } from "./EvmExpectedStateChange"
import type { EvmMessageSimulationError } from "./EvmMessageSimulationError"

export interface EvmMessageSimulationResult {
  expectedStateChanges: Array<EvmExpectedStateChange>
  error: EvmMessageSimulationError | null
}
