// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvmExpectedStateChange } from "./EvmExpectedStateChange";
import type { EvmSimulationError } from "./EvmSimulationError";

export interface EvmSimulationResult {
  expectedStateChanges: Array<EvmExpectedStateChange>;
  error: EvmSimulationError | null;
}
