// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { EvmSimulationResult } from "./EvmSimulationResult";
import type { Warning } from "./Warning";

export interface EvmTransactionScanResult {
  action: Action;
  warnings: Array<Warning>;
  simulationResults: EvmSimulationResult;
}
