// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity"
import type { WarningKind } from "./WarningKind"

export interface Warning {
  kind: WarningKind
  message: string
  severity: Severity
}
