// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EvmSimulationError =
  | { kind: "UNKNOWN_ERROR"; humanReadableError: string }
  | {
      kind: "SIMULATION_FAILED";
      humanReadableError: string;
      parsedErrorMessage: string;
    }
  | { kind: "INVALID_TRANSACTION"; humanReadableError: string };
