// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Price {
  source: string;
  // last_updated_at: number;
  // dollar_value_per_token: number | null;
}
