# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - run: yarn install
      working-directory: ./extension
    - run: yarn typecheck
      working-directory: ./extension
    - run: yarn lint
      working-directory: ./extension
    - run: yarn test
      working-directory: ./extension
    - run: yarn run build --json webpack-stats.json
      working-directory: ./extension
    # Send webpack stats and build information to RelativeCI
    - name: Send webpack stats to RelativeCI
      uses: relative-ci/agent-action@v2
      with:
        webpackStatsFile: ./extension/webpack-stats.json
        key: ${{ secrets.RELATIVE_CI_KEY }}
        token: ${{ secrets.GITHUB_TOKEN }}
