# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build-lint-test

on:
  push:
    branches: [ main, main-v2 ]
  pull_request:
    branches: [ main, main-v2 ]

env:
  NEXT_PUBLIC_ALCHEMY_API_KEY: ${{vars.ALCHEMY_API_KEY}}
  NEXT_PUBLIC_BLOWFISH_API_BASE_URL: ${{vars.BLOWFISH_API_BASE_URL}}
  PLASMO_PUBLIC_BLOWFISH_API_BASE_URL: ${{vars.BLOWFISH_API_BASE_URL}}
  PLASMO_PUBLIC_BLOWFISH_WALLET_IMPERSONATION_AVAILABLE: ${{vars.BLOWFISH_WALLET_IMPERSONATION_AVAILABLE}}
  PLASMO_PUBLIC_BLOWFISH_TRANSACTION_PORTAL_URL: ${{vars.BLOWFISH_TRANSACTION_PORTAL_URL}}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  build-lint-test:

    runs-on: ubuntu-latest
    environment: ci

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - run: pnpm install
    - run: pnpm typecheck
    - run: pnpm lint
    - run: pnpm test
    - run: pnpm build
