name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        working-directory: ./extension
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          workingDir: ./extension
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
