// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EvmMessageSimulationError =
  | { kind: "UNKNOWN_ERROR"; humanReadableError: string }
  | { kind: "UNSUPPORTED_ORDER_TYPE"; humanReadableError: string }
